import React from 'react'
import { Alert,Pressable,StyleSheet,Text,View } from 'react-native'
import { Stack } from 'expo-router'
import { Database,RotateCcw,ShieldCheck } from 'lucide-react-native'
import { colors } from '@/lib/theme'
import { useAppData } from '@/lib/AppDataContext'

export default function BackupScreen(){const {data,resetData}=useAppData();const reset=()=>Alert.alert('Reset Spenza?','All mobile accounts, transactions and bills on this device will be deleted.',[{text:'Cancel',style:'cancel'},{text:'Reset data',style:'destructive',onPress:resetData}]);return <View style={styles.screen}><Stack.Screen options={{headerShown:true,title:'Backup & Restore',headerStyle:{backgroundColor:colors.background},headerTintColor:colors.text}}/><View style={styles.card}><Database color={colors.accent}/><Text style={styles.title}>Local data</Text><Text style={styles.muted}>{data.wallets.length} accounts · {data.transactions.length} transactions · {data.bills.length} bills</Text><Text style={styles.muted}>Your mobile data is currently persisted with AsyncStorage on this device.</Text></View><View style={styles.card}><ShieldCheck color={colors.accent}/><Text style={styles.title}>Cloud backup</Text><Text style={styles.muted}>Cloud Sync is available as a separate Spenza settings screen and will use the same Supabase account as the web app once native authentication is connected.</Text></View><Pressable style={styles.danger} onPress={reset}><RotateCcw color={colors.danger} size={18}/><Text style={styles.dangerText}>Reset local data</Text></Pressable></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background,padding:18,gap:12},card:{borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:17,padding:16,gap:7},title:{color:colors.text,fontWeight:'800',fontSize:16},muted:{color:colors.muted,fontSize:12,lineHeight:18},danger:{height:54,borderWidth:1,borderColor:colors.danger,borderRadius:15,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center',marginTop:6},dangerText:{color:colors.danger,fontWeight:'800'}})
