import React from 'react'
import { Pressable,StyleSheet,Text,View } from 'react-native'
import { Stack } from 'expo-router'
import { Cloud,CloudUpload,RefreshCw } from 'lucide-react-native'
import { colors } from '@/lib/theme'
import { useAppData } from '@/lib/AppDataContext'

export default function CloudSyncScreen(){const {data}=useAppData();return <View style={styles.screen}><Stack.Screen options={{headerShown:true,title:'Cloud Sync',headerStyle:{backgroundColor:colors.background},headerTintColor:colors.text}}/><View style={styles.hero}><Cloud color={colors.accent} size={34}/><Text style={styles.title}>Spenza Cloud Sync</Text><Text style={styles.muted}>This native screen mirrors the web Cloud Sync area. The local mobile dataset is ready to be connected to the same Supabase account used by the web app.</Text></View><View style={styles.card}><Text style={styles.label}>Local mobile data</Text><Text style={styles.value}>{data.wallets.length} accounts</Text><Text style={styles.value}>{data.transactions.length} transactions</Text><Text style={styles.value}>{data.bills.length} bills</Text></View><Pressable style={styles.disabled}><CloudUpload color={colors.muted} size={18}/><Text style={styles.disabledText}>Connect Supabase account</Text></Pressable><Pressable style={styles.disabled}><RefreshCw color={colors.muted} size={18}/><Text style={styles.disabledText}>Sync now</Text></Pressable><Text style={styles.note}>Native Supabase authentication is the remaining wiring step before these actions can safely use your cloud data.</Text></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background,padding:18,gap:12},hero:{alignItems:'center',borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:18,padding:22,gap:8},title:{color:colors.text,fontWeight:'900',fontSize:19},muted:{color:colors.muted,fontSize:12,lineHeight:18,textAlign:'center'},card:{borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:16,padding:16,gap:5},label:{color:colors.muted,fontSize:11,fontWeight:'700',marginBottom:3},value:{color:colors.text,fontWeight:'700'},disabled:{height:52,borderWidth:1,borderColor:colors.line,borderRadius:14,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center',opacity:.65},disabledText:{color:colors.muted,fontWeight:'800'},note:{color:colors.muted,fontSize:11,lineHeight:17,textAlign:'center',paddingHorizontal:10}})
