import React,{useEffect,useState} from 'react'
import { Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native'
import { Stack } from 'expo-router'
import { Cloud,CloudDownload,CloudUpload,LogIn,LogOut,RefreshCw,UserPlus } from 'lucide-react-native'
import { colors } from '@/lib/theme'
import { useAppData } from '@/lib/AppDataContext'
import { clearSignedInUsersCloudData,replaceLocalWithCloud,syncCloudData } from '@/lib/cloudSync'
import { resetSupabasePassword,signInWithEmailPassword,signOutSupabase,signUpWithEmailPassword,supabase } from '@/lib/supabaseClient'

export default function CloudSyncScreen(){
 const {data,replaceData,resetData}=useAppData()
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[signedInEmail,setSignedInEmail]=useState<string|undefined>()
 const [busy,setBusy]=useState(false),[status,setStatus]=useState('')
 useEffect(()=>{supabase.auth.getSession().then(({data:sessionData})=>setSignedInEmail(sessionData.session?.user.email));const {data:listener}=supabase.auth.onAuthStateChange((_event,session)=>setSignedInEmail(session?.user.email));return()=>listener.subscription.unsubscribe()},[])
 const run=async(label:string,fn:()=>Promise<void>)=>{try{setBusy(true);setStatus(label);await fn();setStatus('Done')}catch(error){const message=error instanceof Error?error.message:String(error);setStatus(message);Alert.alert('Cloud Sync',message)}finally{setBusy(false)}}
 const signIn=()=>run('Signing in…',async()=>{await signInWithEmailPassword(email,password);setPassword('')})
 const signUp=()=>run('Creating account…',async()=>{const result=await signUpWithEmailPassword(email,password);setPassword('');if(!result.session)Alert.alert('Check your email','Confirm your email address, then sign in.')})
 const resetPassword=()=>run('Sending reset email…',async()=>{if(!email.trim())throw new Error('Enter your email first.');await resetSupabasePassword(email);Alert.alert('Password reset','Check your email for the password reset link.')})
 const sync=()=>run('Syncing…',async()=>replaceData(await syncCloudData(data)))
 const restore=()=>Alert.alert('Use cloud data?','This replaces the local wallets, transactions and bills with your signed-in cloud data.',[{text:'Cancel',style:'cancel'},{text:'Use cloud data',style:'destructive',onPress:()=>run('Restoring…',async()=>replaceData(await replaceLocalWithCloud(data)))}])
 const signOut=()=>run('Signing out…',async()=>{await signOutSupabase();await resetData();setEmail('')})
 const clearCloud=()=>Alert.alert('Clear cloud data?','This permanently deletes your synced wallets, transactions and bills from this cloud account. Your account stays signed in.',[{text:'Cancel',style:'cancel'},{text:'Clear cloud',style:'destructive',onPress:()=>run('Clearing cloud…',async()=>{await clearSignedInUsersCloudData();await replaceData({...data,sync:{...data.sync,pendingChanges:[],tombstones:[],lastSyncAt:new Date().toISOString()}})})}])
 return <View style={styles.screen}><Stack.Screen options={{headerShown:true,title:'Cloud Sync',headerStyle:{backgroundColor:colors.background},headerTintColor:colors.text}}/><ScrollView contentContainerStyle={styles.wrap} keyboardShouldPersistTaps="handled">
  <View style={styles.hero}><Cloud color={colors.accent} size={34}/><Text style={styles.title}>Spenza Cloud Sync</Text><Text style={styles.muted}>{signedInEmail?`Signed in as ${signedInEmail}`:'Use the same Spenza account as the web app. Mobile and web now share the same cloud records.'}</Text></View>
  {!signedInEmail?<View style={styles.card}><Text style={styles.label}>Email</Text><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="you@example.com" placeholderTextColor={colors.muted} style={styles.input}/><Text style={styles.label}>Password</Text><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor={colors.muted} style={styles.input}/><Pressable disabled={busy} onPress={signIn} style={styles.primary}><LogIn color="#06221d" size={18}/><Text style={styles.primaryText}>Sign in</Text></Pressable><Pressable disabled={busy} onPress={signUp} style={styles.secondary}><UserPlus color={colors.accent} size={18}/><Text style={styles.secondaryText}>Create account</Text></Pressable><Pressable disabled={busy} onPress={resetPassword}><Text style={styles.link}>Forgot password?</Text></Pressable></View>:<>
   <View style={styles.card}><Text style={styles.label}>Local data</Text><Text style={styles.value}>{data.wallets.length} accounts</Text><Text style={styles.value}>{data.transactions.length} transactions</Text><Text style={styles.value}>{data.bills.length} bills</Text><Text style={styles.muted}>{data.sync.pendingChanges.length} pending changes</Text><Text style={styles.muted}>Last sync: {data.sync.lastSyncAt?new Date(data.sync.lastSyncAt).toLocaleString():'Never'}</Text></View>
   <Pressable disabled={busy} onPress={sync} style={styles.primary}><RefreshCw color="#06221d" size={18}/><Text style={styles.primaryText}>Sync now</Text></Pressable>
   <Pressable disabled={busy} onPress={restore} style={styles.secondary}><CloudDownload color={colors.accent} size={18}/><Text style={styles.secondaryText}>Use cloud data</Text></Pressable>
   <Pressable disabled={busy} onPress={sync} style={styles.secondary}><CloudUpload color={colors.accent} size={18}/><Text style={styles.secondaryText}>Merge local + cloud</Text></Pressable>
   <Pressable disabled={busy} onPress={signOut} style={styles.secondary}><LogOut color={colors.accent} size={18}/><Text style={styles.secondaryText}>Sign out & clear local data</Text></Pressable>
   <Pressable disabled={busy} onPress={clearCloud}><Text style={styles.danger}>Clear cloud data</Text></Pressable>
  </>}
  {!!status&&<Text style={styles.status}>{status}</Text>}
 </ScrollView></View>
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},wrap:{padding:18,gap:12,paddingBottom:40},hero:{alignItems:'center',borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:18,padding:22,gap:8},title:{color:colors.text,fontWeight:'900',fontSize:19},muted:{color:colors.muted,fontSize:12,lineHeight:18,textAlign:'center'},card:{borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:16,padding:16,gap:8},label:{color:colors.muted,fontSize:11,fontWeight:'700'},value:{color:colors.text,fontWeight:'700'},input:{height:50,borderWidth:1,borderColor:colors.line,borderRadius:14,color:colors.text,paddingHorizontal:14,backgroundColor:colors.background},primary:{height:52,borderRadius:14,backgroundColor:colors.accent,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center'},primaryText:{color:'#06221d',fontWeight:'800'},secondary:{height:52,borderWidth:1,borderColor:colors.line,borderRadius:14,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center'},secondaryText:{color:colors.text,fontWeight:'800'},link:{color:colors.accent,textAlign:'center',padding:8,fontWeight:'700'},danger:{color:'#ff6b6b',textAlign:'center',padding:12,fontWeight:'800'},status:{color:colors.muted,fontSize:11,textAlign:'center'}})
