import React,{useEffect,useState} from 'react'
import { Pressable,StyleSheet,Switch,Text,TextInput,View } from 'react-native'
import { Stack } from 'expo-router'
import AsyncStorage from '@react-native-async-storage/async-storage'
import { Fingerprint,KeyRound,ShieldCheck } from 'lucide-react-native'
import { colors } from '@/lib/theme'

const KEY='spenza-mobile-security-v1'
export default function SecurityScreen(){const [enabled,setEnabled]=useState(false),[pin,setPin]=useState(''),[biometric,setBiometric]=useState(false);useEffect(()=>{AsyncStorage.getItem(KEY).then(raw=>{if(!raw)return;try{const v=JSON.parse(raw);setEnabled(!!v.enabled);setPin(v.pin||'');setBiometric(!!v.biometric)}catch{}})},[]);const save=async(next:{enabled:boolean;pin:string;biometric:boolean})=>{setEnabled(next.enabled);setPin(next.pin);setBiometric(next.biometric);await AsyncStorage.setItem(KEY,JSON.stringify(next))};return <View style={styles.screen}><Stack.Screen options={{headerShown:true,title:'Security',headerStyle:{backgroundColor:colors.background},headerTintColor:colors.text}}/><View style={styles.card}><View style={styles.row}><ShieldCheck color={colors.accent}/><View style={{flex:1}}><Text style={styles.title}>App Lock</Text><Text style={styles.muted}>Require a PIN when opening the native app.</Text></View><Switch value={enabled} onValueChange={value=>save({enabled:value,pin,biometric})}/></View>{enabled&&<View style={styles.pinWrap}><KeyRound color={colors.muted} size={18}/><TextInput value={pin} onChangeText={value=>{const next=value.replace(/\D/g,'').slice(0,6);save({enabled,pin:next,biometric})}} keyboardType="number-pad" secureTextEntry maxLength={6} placeholder="4–6 digit PIN" placeholderTextColor={colors.muted} style={styles.input}/></View>}</View><View style={styles.card}><View style={styles.row}><Fingerprint color={colors.accent}/><View style={{flex:1}}><Text style={styles.title}>Biometric unlock</Text><Text style={styles.muted}>Preference is stored now; native Face ID / fingerprint enforcement will activate when secure authentication is wired.</Text></View><Switch value={biometric} onValueChange={value=>save({enabled,pin,biometric:value})}/></View></View></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background,padding:18,gap:12},card:{borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:17,padding:16,gap:14},row:{flexDirection:'row',alignItems:'center',gap:12},title:{color:colors.text,fontWeight:'800',fontSize:15},muted:{color:colors.muted,fontSize:11,lineHeight:16,marginTop:3},pinWrap:{flexDirection:'row',alignItems:'center',gap:8},input:{flex:1,height:48,borderWidth:1,borderColor:colors.line,borderRadius:13,color:colors.text,paddingHorizontal:12,backgroundColor:colors.background}})
