import React,{useState} from 'react'
import { Alert,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native'
import { Pencil,Plus,Star,Trash2,X } from 'lucide-react-native'
import { Screen } from '@/components/Screen'
import { colors } from '@/lib/theme'
import { useAppData } from '@/lib/AppDataContext'
import type { Currency,Wallet } from '@/lib/types'

const money=(value:number,currency:Currency)=>currency==='USD'?`$${value.toFixed(2)}`:`${Math.round(value).toLocaleString()} LBP`
type Form={id?:string;name:string;currency:Currency;openingBalance:string}

export default function AccountsScreen(){
 const {data,addWallet,updateWallet,deleteWallet,setDefaultWallet,walletBalance}=useAppData();const [form,setForm]=useState<Form|null>(null)
 const openNew=()=>setForm({name:'',currency:'USD',openingBalance:'0'}),edit=(w:Wallet)=>setForm({id:w.id,name:w.name,currency:w.currency,openingBalance:String(w.openingBalance)})
 const save=async()=>{if(!form?.name.trim())return;const openingBalance=Number(form.openingBalance)||0;if(form.id){const old=data.wallets.find(w=>w.id===form.id);if(old)await updateWallet({...old,name:form.name.trim(),currency:form.currency,openingBalance})}else await addWallet({name:form.name.trim(),currency:form.currency,openingBalance});setForm(null)}
 const remove=(w:Wallet)=>Alert.alert('Delete account?',`${w.name} and its related transactions and bills will be removed.`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>deleteWallet(w.id)}])
 return <Screen title="Accounts"><ScrollView contentContainerStyle={styles.wrap}>
  <View style={styles.head}><Text style={styles.muted}>Tap the star to choose your default account.</Text><Pressable style={styles.addCircle} onPress={openNew}><Plus color="#06221d" size={20}/></Pressable></View>
  {data.wallets.length===0?<Text style={styles.empty}>No accounts yet. Add your first account.</Text>:data.wallets.map((w,i)=><View key={w.id} style={[styles.card,i%2===1&&styles.cardAlt]}><View style={styles.top}><Text style={styles.currency}>{w.currency}</Text><View style={styles.actions}><Pressable style={styles.icon} onPress={()=>setDefaultWallet(w.id)}><Star size={17} color={data.defaultWalletId===w.id?colors.accent:colors.muted} fill={data.defaultWalletId===w.id?colors.accent:'transparent'}/></Pressable><Pressable style={styles.icon} onPress={()=>edit(w)}><Pencil size={17} color={colors.text}/></Pressable><Pressable style={styles.icon} onPress={()=>remove(w)}><Trash2 size={17} color={colors.danger}/></Pressable></View></View><Text style={styles.name}>{w.name}</Text><Text style={styles.balance}>{money(walletBalance(w),w.currency)}</Text><Text style={styles.muted}>Opening {money(w.openingBalance,w.currency)}{data.defaultWalletId===w.id?' · Default':''}</Text></View>)}
 </ScrollView><Modal visible={!!form} transparent animationType="slide" onRequestClose={()=>setForm(null)}>{form&&<View style={styles.backdrop}><View style={styles.sheet}><View style={styles.sheetHead}><View><Text style={styles.eyebrow}>{form.id?'EDIT':'NEW'} ACCOUNT</Text><Text style={styles.sheetTitle}>{form.id?'Edit Account':'Add Account'}</Text></View><Pressable onPress={()=>setForm(null)}><X color={colors.text}/></Pressable></View><Text style={styles.label}>Account name</Text><TextInput value={form.name} onChangeText={name=>setForm({...form,name})} style={styles.input}/><Text style={styles.label}>Currency</Text><View style={styles.segment}>{(['USD','LBP'] as Currency[]).map(c=><Pressable key={c} onPress={()=>setForm({...form,currency:c})} style={[styles.segmentBtn,form.currency===c&&styles.segmentActive]}><Text style={[styles.segmentText,form.currency===c&&styles.segmentTextActive]}>{c}</Text></Pressable>)}</View><Text style={styles.label}>Opening balance</Text><TextInput value={form.openingBalance} onChangeText={openingBalance=>setForm({...form,openingBalance})} keyboardType="decimal-pad" style={styles.input}/><Pressable style={styles.save} onPress={save}><Text style={styles.saveText}>{form.id?'Save Account':'Create Account'}</Text></Pressable></View></View>}</Modal></Screen>
}
const styles=StyleSheet.create({wrap:{gap:10,paddingBottom:34},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},muted:{color:colors.muted,fontSize:11,lineHeight:16},addCircle:{width:42,height:42,borderRadius:21,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center'},empty:{color:colors.muted,marginTop:8},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:16,gap:5},cardAlt:{backgroundColor:colors.surface2},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},actions:{flexDirection:'row',gap:7},icon:{width:34,height:34,borderRadius:10,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},currency:{color:colors.accent,fontSize:11,fontWeight:'900'},name:{color:colors.text,fontSize:17,fontWeight:'900'},balance:{color:colors.text,fontSize:24,fontWeight:'900'},backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.65)',justifyContent:'flex-end'},sheet:{backgroundColor:colors.background,borderTopLeftRadius:24,borderTopRightRadius:24,padding:20,gap:11,borderWidth:1,borderColor:colors.line},sheetHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:4},eyebrow:{color:colors.accent,fontSize:10,fontWeight:'900',letterSpacing:1},sheetTitle:{color:colors.text,fontSize:21,fontWeight:'900'},label:{color:colors.text,fontSize:12,fontWeight:'700'},input:{height:50,borderRadius:15,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,color:colors.text,paddingHorizontal:14},segment:{flexDirection:'row',backgroundColor:colors.surface,borderRadius:14,padding:4},segmentBtn:{flex:1,padding:11,alignItems:'center',borderRadius:10},segmentActive:{backgroundColor:colors.accent},segmentText:{color:colors.muted,fontWeight:'700'},segmentTextActive:{color:'#06221d'},save:{height:52,borderRadius:15,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center',marginTop:4},saveText:{color:'#06221d',fontWeight:'900'}})
