import React,{useMemo,useState,type ReactNode} from 'react'
import { Alert,Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native'
import * as ImagePicker from 'expo-image-picker'
import { Camera,Images,Plus } from 'lucide-react-native'
import { Screen } from '@/components/Screen'
import { colors } from '@/lib/theme'
import { useAppData } from '@/lib/AppDataContext'
import type { Currency,TransactionType } from '@/lib/types'

export default function AddTransactionScreen(){
 const {data,addTransaction,addCategory}=useAppData()
 const [type,setType]=useState<TransactionType>('expense')
 const [walletId,setWalletId]=useState(data.defaultWalletId||data.wallets[0]?.id||'')
 const [toWalletId,setToWalletId]=useState(data.wallets.find(w=>w.id!==walletId)?.id||'')
 const [amount,setAmount]=useState(''),[entryCurrency,setEntryCurrency]=useState<Currency>('USD')
 const [category,setCategory]=useState(data.categories[0]||'Other'),[description,setDescription]=useState(''),[note,setNote]=useState('')
 const [date,setDate]=useState(new Date().toISOString().slice(0,10)),[images,setImages]=useState<string[]>([]),[newCategory,setNewCategory]=useState('')
 const wallet=data.wallets.find(w=>w.id===walletId),toWallet=data.wallets.find(w=>w.id===toWalletId)
 const converted=useMemo(()=>{const n=Number(amount)||0;if(!wallet||entryCurrency===wallet.currency)return n;return entryCurrency==='USD'?n*data.usdToLbpRate:n/data.usdToLbpRate},[amount,entryCurrency,wallet,data.usdToLbpRate])
 const transferRate=useMemo(()=>{if(!wallet||!toWallet||wallet.currency===toWallet.currency)return 1;return wallet.currency==='USD'?data.usdToLbpRate:1/data.usdToLbpRate},[wallet,toWallet,data.usdToLbpRate])
 const pickGallery=async()=>{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.8,allowsMultipleSelection:true});if(!r.canceled)setImages(v=>[...v,...r.assets.map(a=>a.uri)].slice(0,5))}
 const takePhoto=async()=>{const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted){Alert.alert('Camera permission','Allow camera access to take a receipt photo.');return}const r=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.8});if(!r.canceled)setImages(v=>[...v,r.assets[0].uri].slice(0,5))}
 const save=async()=>{if(!wallet){Alert.alert('Account required','Add or select an account first.');return}if(!(Number(amount)>0)){Alert.alert('Amount required','Enter a valid amount.');return}if(type==='transfer'&&(!toWallet||toWallet.id===wallet.id)){Alert.alert('Destination required','Choose a different destination account.');return}await addTransaction({type,title:description.trim()||(type==='expense'?category:type==='income'?'Transaction':'Transfer'),category:type==='transfer'?'Transfer':category,amount:converted,walletId:wallet.id,toWalletId:type==='transfer'?toWallet?.id:undefined,date,note:note.trim()||undefined,noteImages:images.length?images:undefined,exchangeRate:type==='transfer'?transferRate:(entryCurrency===wallet.currency?undefined:(entryCurrency==='USD'?data.usdToLbpRate:1/data.usdToLbpRate))});setAmount('');setDescription('');setNote('');setImages([]);Alert.alert('Saved','Transaction added successfully.')}
 const createCategory=async()=>{const value=newCategory.trim();if(!value)return;await addCategory(value);setCategory(value);setNewCategory('')}
 return <Screen title="Add Transaction">
  <ScrollView contentContainerStyle={styles.wrap} keyboardShouldPersistTaps="handled">
   <View style={styles.segment}>{(['expense','income','transfer'] as TransactionType[]).map(v=><Pressable key={v} onPress={()=>setType(v)} style={[styles.segmentBtn,type===v&&styles.segmentActive]}><Text style={[styles.segmentText,type===v&&styles.segmentTextActive]}>{v[0].toUpperCase()+v.slice(1)}</Text></Pressable>)}</View>
   <Field label="Date"><TextInput value={date} onChangeText={setDate} style={styles.input}/></Field>
   <Field label="Account"><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{data.wallets.map(w=><Pressable key={w.id} onPress={()=>{setWalletId(w.id);setEntryCurrency(w.currency);if(toWalletId===w.id)setToWalletId(data.wallets.find(x=>x.id!==w.id)?.id||'')}} style={[styles.chip,walletId===w.id&&styles.chipActive]}><Text style={[styles.chipText,walletId===w.id&&styles.chipTextActive]}>{w.name} · {w.currency}</Text></Pressable>)}</ScrollView>{data.wallets.length===0&&<Text style={styles.hint}>Add an account from Settings → Accounts first.</Text>}</Field>
   {type==='transfer'&&<Field label="To Account"><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{data.wallets.filter(w=>w.id!==walletId).map(w=><Pressable key={w.id} onPress={()=>setToWalletId(w.id)} style={[styles.chip,toWalletId===w.id&&styles.chipActive]}><Text style={[styles.chipText,toWalletId===w.id&&styles.chipTextActive]}>{w.name} · {w.currency}</Text></Pressable>)}</ScrollView></Field>}
   <Field label="Amount"><View style={styles.amountRow}><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" style={[styles.input,{flex:1}]}/><View style={styles.currencyToggle}>{(['USD','LBP'] as Currency[]).map(c=><Pressable key={c} onPress={()=>setEntryCurrency(c)} style={[styles.currencyBtn,entryCurrency===c&&styles.currencyActive]}><Text style={[styles.currencyText,entryCurrency===c&&styles.currencyTextActive]}>{c}</Text></Pressable>)}</View></View>{wallet&&entryCurrency!==wallet.currency&&Number(amount)>0&&<Text style={styles.hint}>Will save as {wallet.currency==='USD'?`$${converted.toFixed(2)}`:`${Math.round(converted).toLocaleString()} LBP`} in {wallet.name}</Text>}{type==='transfer'&&wallet&&toWallet&&wallet.currency!==toWallet.currency&&Number(amount)>0&&<Text style={styles.hint}>Destination receives {toWallet.currency==='USD'?`$${(converted*transferRate).toFixed(2)}`:`${Math.round(converted*transferRate).toLocaleString()} LBP`}.</Text>}</Field>
   {type!=='transfer'&&<Field label="Category"><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{data.categories.map(c=><Pressable key={c} onPress={()=>setCategory(c)} style={[styles.chip,category===c&&styles.chipActive]}><Text style={[styles.chipText,category===c&&styles.chipTextActive]}>{c}</Text></Pressable>)}</ScrollView><View style={styles.newCategory}><TextInput value={newCategory} onChangeText={setNewCategory} placeholder="New category" placeholderTextColor={colors.muted} style={[styles.input,{flex:1}]}/><Pressable onPress={createCategory} style={styles.smallAdd}><Plus color="#06221d" size={18}/></Pressable></View></Field>}
   <Field label="Description" optional><View style={styles.inputRow}><TextInput value={description} onChangeText={setDescription} style={[styles.input,{paddingRight:50}]}/><Pressable onPress={takePhoto} style={styles.iconButton}><Camera color={colors.accent} size={20}/></Pressable></View></Field>
   <View style={styles.photoActions}><Pressable style={styles.photoAction} onPress={takePhoto}><Camera color={colors.accent} size={20}/><Text style={styles.photoText}>Camera</Text></Pressable><Pressable style={styles.photoAction} onPress={pickGallery}><Images color={colors.accent} size={20}/><Text style={styles.photoText}>Gallery</Text></Pressable></View>
   {images.length>0&&<ScrollView horizontal contentContainerStyle={styles.photos}>{images.map((uri,i)=><Pressable key={`${uri}-${i}`} onPress={()=>setImages(v=>v.filter((_,x)=>x!==i))}><Image source={{uri}} style={styles.photo}/></Pressable>)}</ScrollView>}
   <Field label="Note" optional><TextInput value={note} onChangeText={setNote} style={styles.input}/></Field>
   <Pressable style={styles.save} onPress={save}><Text style={styles.saveText}>Save Transaction</Text></Pressable>
  </ScrollView>
 </Screen>
}

function Field({label,optional,children}:{label:string;optional?:boolean;children:ReactNode}){return <View style={styles.field}><View style={styles.labelRow}><Text style={styles.label}>{label}</Text>{optional&&<Text style={styles.optional}>Optional</Text>}</View>{children}</View>}

const styles=StyleSheet.create({wrap:{gap:14,paddingBottom:40},field:{gap:7},labelRow:{flexDirection:'row',gap:7,alignItems:'center'},label:{color:colors.text,fontSize:12,fontWeight:'700'},optional:{color:colors.muted,fontSize:10},input:{height:50,borderWidth:1,borderColor:colors.line,borderRadius:15,backgroundColor:colors.surface,color:colors.text,paddingHorizontal:14},inputRow:{position:'relative'},iconButton:{position:'absolute',right:7,top:7,width:36,height:36,alignItems:'center',justifyContent:'center'},segment:{flexDirection:'row',backgroundColor:colors.surface,borderRadius:14,padding:4},segmentBtn:{flex:1,paddingVertical:11,alignItems:'center',borderRadius:10},segmentActive:{backgroundColor:colors.accent},segmentText:{color:colors.muted,fontWeight:'700',fontSize:12},segmentTextActive:{color:'#06221d'},chips:{gap:8},chip:{borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,paddingHorizontal:13,paddingVertical:10,borderRadius:999},chipActive:{backgroundColor:colors.accent,borderColor:colors.accent},chipText:{color:colors.text,fontWeight:'700'},chipTextActive:{color:'#06221d'},amountRow:{flexDirection:'row',gap:8},currencyToggle:{flexDirection:'row',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:15,padding:4},currencyBtn:{paddingHorizontal:10,justifyContent:'center',borderRadius:11},currencyActive:{backgroundColor:colors.accent},currencyText:{color:colors.muted,fontWeight:'700',fontSize:11},currencyTextActive:{color:'#06221d'},hint:{color:colors.muted,fontSize:11},newCategory:{flexDirection:'row',gap:8},smallAdd:{width:50,height:50,borderRadius:14,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center'},photoActions:{flexDirection:'row',gap:10},photoAction:{flex:1,minHeight:50,borderWidth:1,borderColor:colors.line,borderRadius:15,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},photoText:{color:colors.text,fontWeight:'700'},photos:{gap:8},photo:{width:72,height:72,borderRadius:12},save:{height:54,borderRadius:15,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center',marginTop:4},saveText:{color:'#06221d',fontWeight:'800'}})
