import React,{useMemo,useState} from 'react'
import { Alert,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native'
import { CalendarClock,Check,Pencil,Plus,SkipForward,Trash2,X } from 'lucide-react-native'
import { Screen } from '@/components/Screen'
import { colors } from '@/lib/theme'
import { useAppData } from '@/lib/AppDataContext'
import type { Bill,BillRecurrence } from '@/lib/types'

const today=()=>new Date().toISOString().slice(0,10)
const money=(n:number,c:'USD'|'LBP')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:c==='LBP'?0:2}).format(n)
type Filter='all'|'upcoming'|'overdue'
type Form={id?:string;name:string;amount:string;walletId:string;category:string;dueDate:string;recurrence:BillRecurrence;reminderDays:0|1|3|7;note:string}

export default function BillsScreen(){
 const {data,upsertBill,deleteBill,markBillPaid,skipBill}=useAppData()
 const [filter,setFilter]=useState<Filter>('all')
 const [form,setForm]=useState<Form|null>(null)
 const sorted=useMemo(()=>[...data.bills].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),[data.bills])
 const visible=sorted.filter(b=>filter==='all'||(filter==='overdue'?b.dueDate<today()&&!(b.recurrence==='once'&&b.lastPaidDate):b.dueDate>=today()))
 const openNew=()=>setForm({name:'',amount:'',walletId:data.defaultWalletId||data.wallets[0]?.id||'',category:data.categories.includes('Bills')?'Bills':data.categories[0]||'Other',dueDate:today(),recurrence:'monthly',reminderDays:3,note:''})
 const edit=(b:Bill)=>setForm({id:b.id,name:b.name,amount:String(b.amount),walletId:b.walletId,category:b.category,dueDate:b.dueDate,recurrence:b.recurrence,reminderDays:b.reminderDays,note:b.note||''})
 const save=async()=>{if(!form)return;const amount=Number(form.amount);if(!form.name.trim()||!form.walletId||!(amount>0)){Alert.alert('Missing details','Enter a bill name, amount and account.');return}const old=data.bills.find(b=>b.id===form.id);await upsertBill({id:form.id||`${Date.now()}-${Math.random().toString(16).slice(2)}`,name:form.name.trim(),amount,walletId:form.walletId,category:form.category,dueDate:form.dueDate,recurrence:form.recurrence,reminderDays:form.reminderDays,note:form.note.trim()||undefined,lastPaidDate:old?.lastPaidDate,createdAt:old?.createdAt});setForm(null)}
 const remove=(b:Bill)=>Alert.alert('Delete bill?',`${b.name} will be removed. Existing transactions will stay.`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>deleteBill(b.id)}])
 const skip=(b:Bill)=>Alert.alert('Skip this payment?',`Move ${b.name} to its next ${b.recurrence} due date without changing your balance?`,[{text:'Cancel',style:'cancel'},{text:'Skip',onPress:()=>skipBill(b.id)}])
 return <Screen title="Bills">
  <ScrollView contentContainerStyle={styles.wrap}>
   <View style={styles.headRow}><View style={{flex:1}}><Text style={styles.title}>Scheduled payments</Text><Text style={styles.muted}>Bills affect your account only after you confirm Paid.</Text></View><Pressable style={styles.add} onPress={openNew}><Plus color="#06221d" size={20}/></Pressable></View>
   <View style={styles.filters}>{(['all','upcoming','overdue'] as Filter[]).map(v=><Pressable key={v} onPress={()=>setFilter(v)} style={[styles.filter,filter===v&&styles.filterActive]}><Text style={[styles.filterText,filter===v&&styles.filterTextActive]}>{v[0].toUpperCase()+v.slice(1)}</Text></Pressable>)}</View>
   {!data.wallets.length&&<View style={styles.empty}><Text style={styles.muted}>Create an account before adding bills.</Text></View>}
   {visible.map(b=>{const w=data.wallets.find(x=>x.id===b.walletId);const paid=b.recurrence==='once'&&!!b.lastPaidDate;const overdue=!paid&&b.dueDate<today();return <View key={b.id} style={[styles.card,overdue&&styles.overdue]}><View style={styles.billIcon}><CalendarClock color={colors.accent} size={20}/></View><View style={{flex:1,gap:3}}><View style={styles.billTop}><Text style={styles.billName}>{b.name}</Text><Text style={[styles.status,overdue&&{color:colors.danger},paid&&{color:colors.accent}]}>{paid?'Paid':overdue?'Overdue':'Due'} {new Date(`${b.dueDate}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</Text></View><Text style={styles.amount}>{money(b.amount,w?.currency||'USD')}</Text><Text style={styles.muted}>{w?.name||'Missing account'} · {b.category} · {b.recurrence==='once'?'One-time':b.recurrence} · {b.reminderDays===0?'Due day':`${b.reminderDays}d reminder`}</Text><View style={styles.actions}><Pressable disabled={paid} style={[styles.action,paid&&{opacity:.35}]} onPress={()=>markBillPaid(b.id)}><Check color={colors.accent} size={17}/><Text style={styles.actionText}>Paid</Text></Pressable>{b.recurrence!=='once'&&<Pressable style={styles.action} onPress={()=>skip(b)}><SkipForward color={colors.text} size={17}/><Text style={styles.actionText}>Skip</Text></Pressable>}<Pressable style={styles.iconAction} onPress={()=>edit(b)}><Pencil color={colors.text} size={17}/></Pressable><Pressable style={styles.iconAction} onPress={()=>remove(b)}><Trash2 color={colors.danger} size={17}/></Pressable></View></View></View>})}
   {!!data.wallets.length&&!visible.length&&<View style={styles.empty}><Text style={styles.muted}>No bills in this view.</Text></View>}
  </ScrollView>
  <Modal visible={!!form} transparent animationType="slide" onRequestClose={()=>setForm(null)}>{form&&<View style={styles.modalBack}><View style={styles.sheet}><View style={styles.sheetHead}><View><Text style={styles.eyebrow}>{form.id?'EDIT':'NEW'} BILL</Text><Text style={styles.sheetTitle}>{form.id?'Edit Bill':'Add Bill'}</Text></View><Pressable onPress={()=>setForm(null)}><X color={colors.text}/></Pressable></View><ScrollView contentContainerStyle={{gap:12,paddingBottom:24}}>
   <Label text="Bill name"><TextInput style={styles.input} value={form.name} onChangeText={name=>setForm({...form,name})}/></Label>
   <Label text="Amount"><TextInput style={styles.input} keyboardType="decimal-pad" value={form.amount} onChangeText={amount=>setForm({...form,amount})}/></Label>
   <Label text="Account"><ScrollView horizontal contentContainerStyle={styles.chips} showsHorizontalScrollIndicator={false}>{data.wallets.map(w=><Chip key={w.id} text={`${w.name} · ${w.currency}`} active={form.walletId===w.id} onPress={()=>setForm({...form,walletId:w.id})}/>)}</ScrollView></Label>
   <Label text="Category"><ScrollView horizontal contentContainerStyle={styles.chips} showsHorizontalScrollIndicator={false}>{data.categories.map(c=><Chip key={c} text={c} active={form.category===c} onPress={()=>setForm({...form,category:c})}/>)}</ScrollView></Label>
   <Label text="Due date"><TextInput style={styles.input} value={form.dueDate} onChangeText={dueDate=>setForm({...form,dueDate})}/></Label>
   <Label text="Repeat"><View style={styles.filters}>{(['once','monthly','yearly'] as BillRecurrence[]).map(v=><Chip key={v} text={v==='once'?'One-time':v} active={form.recurrence===v} onPress={()=>setForm({...form,recurrence:v})}/>)}</View></Label>
   <Label text="Reminder"><View style={styles.filters}>{([0,1,3,7] as const).map(v=><Chip key={v} text={v===0?'Due date':v===7?'1 week':`${v} day${v===1?'':'s'}`} active={form.reminderDays===v} onPress={()=>setForm({...form,reminderDays:v})}/>)}</View></Label>
   <Label text="Note"><TextInput style={styles.input} value={form.note} onChangeText={note=>setForm({...form,note})}/></Label>
   <Pressable style={styles.save} onPress={save}><Text style={styles.saveText}>{form.id?'Save Bill':'Create Bill'}</Text></Pressable>
  </ScrollView></View></View>}</Modal>
 </Screen>
}

function Label({text,children}:{text:string;children:React.ReactNode}){return <View style={{gap:7}}><Text style={styles.label}>{text}</Text>{children}</View>}
function Chip({text,active,onPress}:{text:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,active&&styles.filterActive]}><Text style={[styles.chipText,active&&styles.filterTextActive]}>{text}</Text></Pressable>}

const styles=StyleSheet.create({wrap:{gap:12,paddingBottom:36},headRow:{flexDirection:'row',alignItems:'center',gap:12},title:{color:colors.text,fontSize:16,fontWeight:'800'},muted:{color:colors.muted,fontSize:11,lineHeight:16},add:{width:42,height:42,borderRadius:21,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center'},filters:{flexDirection:'row',gap:8,flexWrap:'wrap'},filter:{flex:1,minWidth:90,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,paddingVertical:10,borderRadius:12,alignItems:'center'},filterActive:{backgroundColor:colors.accent,borderColor:colors.accent},filterText:{color:colors.text,fontWeight:'700',fontSize:12},filterTextActive:{color:'#06221d'},card:{flexDirection:'row',gap:12,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:14},overdue:{borderColor:colors.danger},billIcon:{width:40,height:40,borderRadius:12,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},billTop:{flexDirection:'row',justifyContent:'space-between',gap:8},billName:{color:colors.text,fontWeight:'800',flex:1},status:{color:colors.muted,fontSize:10,fontWeight:'700'},amount:{color:colors.text,fontSize:20,fontWeight:'800'},actions:{flexDirection:'row',gap:8,marginTop:8,alignItems:'center',flexWrap:'wrap'},action:{flexDirection:'row',gap:5,alignItems:'center',borderWidth:1,borderColor:colors.line,borderRadius:10,paddingHorizontal:9,paddingVertical:7},actionText:{color:colors.text,fontSize:11,fontWeight:'700'},iconAction:{width:34,height:34,borderRadius:10,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},empty:{padding:20,alignItems:'center'},modalBack:{flex:1,backgroundColor:'rgba(0,0,0,.65)',justifyContent:'flex-end'},sheet:{maxHeight:'92%',backgroundColor:colors.background,borderTopLeftRadius:24,borderTopRightRadius:24,padding:18,borderWidth:1,borderColor:colors.line},sheetHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:16},eyebrow:{color:colors.accent,fontSize:10,fontWeight:'800',letterSpacing:1},sheetTitle:{color:colors.text,fontSize:22,fontWeight:'900'},label:{color:colors.text,fontSize:12,fontWeight:'700'},input:{height:50,borderWidth:1,borderColor:colors.line,borderRadius:14,backgroundColor:colors.surface,color:colors.text,paddingHorizontal:13},chips:{gap:8},chip:{borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,paddingHorizontal:12,paddingVertical:9,borderRadius:999},chipText:{color:colors.text,fontSize:11,fontWeight:'700'},save:{height:54,borderRadius:15,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center'},saveText:{color:'#06221d',fontWeight:'900'}})
