import React,{useMemo,useState} from 'react'
import { Pressable,ScrollView,StyleSheet,Text,View } from 'react-native'
import { useRouter } from 'expo-router'
import { Bell,ChevronLeft,ChevronRight } from 'lucide-react-native'
import { Screen } from '@/components/Screen'
import { colors } from '@/lib/theme'
import { useAppData } from '@/lib/AppDataContext'
import type { Currency,Transaction } from '@/lib/types'

const money=(value:number,currency:Currency)=>currency==='USD'?`$${value.toFixed(2)}`:`${Math.round(value).toLocaleString()} LBP`
type Period='daily'|'monthly'|'yearly'
const isoToday=()=>new Date().toISOString().slice(0,10)
const inPeriod=(date:string,period:Period,anchor:string)=>period==='daily'?date===anchor:period==='monthly'?date.slice(0,7)===anchor.slice(0,7):date.slice(0,4)===anchor.slice(0,4)
const shift=(anchor:string,period:Period,amount:number)=>{const d=new Date(`${anchor}T12:00:00`);if(period==='daily')d.setDate(d.getDate()+amount);else if(period==='monthly')d.setMonth(d.getMonth()+amount);else d.setFullYear(d.getFullYear()+amount);return d.toISOString().slice(0,10)}
const label=(anchor:string,period:Period)=>{const d=new Date(`${anchor}T12:00:00`);return period==='daily'?d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):period==='monthly'?d.toLocaleDateString('en-US',{month:'long',year:'numeric'}):String(d.getFullYear())}

export default function HomeScreen(){
 const router=useRouter();const {data}=useAppData();const [period,setPeriod]=useState<Period>('daily'),[anchor,setAnchor]=useState(isoToday()),[walletId,setWalletId]=useState(data.defaultWalletId||data.wallets[0]?.id||'')
 const wallet=data.wallets.find(w=>w.id===walletId)||data.wallets[0]
 const tx=useMemo(()=>wallet?data.transactions.filter(t=>t.walletId===wallet.id&&inPeriod(t.date,period,anchor)):[],[data.transactions,wallet,period,anchor])
 const income=tx.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0),expense=tx.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0),net=income-expense
 const categories=useMemo(()=>{const map=new Map<string,number>();for(const t of tx)if(t.type==='expense')map.set(t.category,(map.get(t.category)||0)+t.amount);return [...map.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)},[tx])
 const recent=[...tx].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)).slice(0,5)
 return <Screen title="Spenza"><ScrollView contentContainerStyle={styles.wrap}>
  <View style={styles.heroHead}><View><Text style={styles.eyebrow}>SPENZA</Text><Text style={styles.greeting}>Good Morning! 👋</Text></View><Pressable style={styles.bell} onPress={()=>router.push('/notifications')}><Bell color={colors.text} size={20}/>{data.bills.some(b=>b.dueDate<=isoToday())&&<View style={styles.dot}/>}</Pressable></View>
  <View style={styles.periods}>{(['daily','monthly','yearly'] as Period[]).map(p=><Pressable key={p} onPress={()=>setPeriod(p)} style={[styles.period,period===p&&styles.selected]}><Text style={[styles.periodText,period===p&&styles.selectedText]}>{p[0].toUpperCase()+p.slice(1)}</Text></Pressable>)}</View>
  {!!data.wallets.length&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{data.wallets.map(w=><Pressable key={w.id} onPress={()=>setWalletId(w.id)} style={[styles.chip,wallet?.id===w.id&&styles.selected]}><Text style={[styles.chipText,wallet?.id===w.id&&styles.selectedText]}>{w.name} · {w.currency}</Text></Pressable>)}</ScrollView>}
  <View style={styles.monthCard}><Pressable onPress={()=>setAnchor(v=>shift(v,period,-1))}><ChevronLeft color={colors.text}/></Pressable><View style={{alignItems:'center',flex:1}}><Text style={styles.monthLabel}>{label(anchor,period)}</Text><Text style={styles.muted}>{wallet?`${wallet.name} · ${period} net`:`${period} overview`}</Text><Text style={styles.net}>{wallet?money(net,wallet.currency):'—'}</Text></View><Pressable onPress={()=>setAnchor(v=>shift(v,period,1))}><ChevronRight color={colors.text}/></Pressable></View>
  <View style={styles.summary}><Summary label="Income" value={wallet?money(income,wallet.currency):'—'} color={colors.income}/><Summary label="Exp." value={wallet?money(expense,wallet.currency):'—'} color={colors.danger}/><Summary label="Total" value={wallet?money(net,wallet.currency):'—'} /></View>
  <View style={styles.sectionHead}><Text style={styles.section}>{label(anchor,period)} Overview</Text><Pressable onPress={()=>router.push('/(tabs)/insights')}><Text style={styles.link}>See All</Text></Pressable></View>
  <View style={styles.overview}><View style={styles.overviewCard}><Text style={styles.muted}>Total Income</Text><Text style={styles.overviewValue}>{wallet?money(income,wallet.currency):'—'}</Text><Text style={styles.muted}>Expenses {wallet?money(expense,wallet.currency):'—'}</Text></View><View style={styles.overviewCard}><Text style={styles.muted}>Top Categories</Text>{categories.slice(0,3).map(c=><View key={c.name} style={styles.miniRow}><Text style={styles.miniName}>{c.name}</Text><Text style={styles.miniValue}>{wallet?money(c.value,wallet.currency):''}</Text></View>)}{!categories.length&&<Text style={styles.muted}>No spending yet</Text>}</View></View>
  <View style={styles.categoryCard}><Text style={styles.section}>Expenses by Category</Text>{categories.slice(0,5).map(c=>{const pct=expense?Math.round(c.value/expense*100):0;return <View key={c.name} style={styles.categoryRow}><View style={{flex:1}}><View style={styles.miniRow}><Text style={styles.miniName}>{c.name}</Text><Text style={styles.miniValue}>{pct}%</Text></View><View style={styles.bar}><View style={[styles.barFill,{width:`${pct}%` as any}]}/></View></View></View>})}{!categories.length&&<Text style={styles.muted}>No expense data yet.</Text>}</View>
  <View style={styles.sectionHead}><Text style={styles.section}>Recent Transactions</Text><Pressable onPress={()=>router.push('/(tabs)/transactions')}><Text style={styles.link}>See All</Text></Pressable></View>
  {recent.length?recent.map(t=><TransactionRow key={t.id} t={t} accountName={wallet?.name||'Account'} currency={wallet?.currency||'USD'}/>):<Text style={styles.muted}>No transactions for this account and period.</Text>}
 </ScrollView></Screen>
}
function Summary({label,value,color}:{label:string;value:string;color?:string}){return <View style={styles.summaryCard}><Text style={styles.muted}>{label}</Text><Text style={[styles.summaryValue,color?{color}:null]}>{value}</Text></View>}
function TransactionRow({t,accountName,currency}:{t:Transaction;accountName:string;currency:Currency}){return <View style={styles.tx}><View style={{flex:1}}><Text style={styles.txCategory}>{t.category}</Text><Text style={styles.muted}>{accountName}{t.title?` · ${t.title}`:''}</Text></View><Text style={[styles.txAmount,{color:t.type==='income'?colors.income:t.type==='expense'?colors.danger:colors.text}]}>{t.type==='income'?'+':t.type==='expense'?'-':'−'}{money(t.amount,currency)}</Text></View>}
const styles=StyleSheet.create({wrap:{gap:11,paddingBottom:34},heroHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{color:colors.accent,fontSize:10,fontWeight:'900',letterSpacing:1.2},greeting:{color:colors.text,fontSize:22,fontWeight:'900',marginTop:3},bell:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},dot:{position:'absolute',right:9,top:8,width:7,height:7,borderRadius:4,backgroundColor:colors.danger},periods:{flexDirection:'row',gap:8},period:{flex:1,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,paddingVertical:9,borderRadius:12,alignItems:'center'},periodText:{color:colors.text,fontSize:11,fontWeight:'700'},selected:{backgroundColor:colors.accent,borderColor:colors.accent},selectedText:{color:'#06221d'},chips:{gap:8},chip:{borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,paddingHorizontal:12,paddingVertical:9,borderRadius:999},chipText:{color:colors.text,fontSize:11,fontWeight:'700'},monthCard:{borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:20,padding:14,flexDirection:'row',alignItems:'center'},monthLabel:{color:colors.text,fontWeight:'800',fontSize:15},muted:{color:colors.muted,fontSize:11,lineHeight:16},net:{color:colors.text,fontSize:25,fontWeight:'900',marginTop:5},summary:{flexDirection:'row',gap:8},summaryCard:{flex:1,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:15,padding:12},summaryValue:{color:colors.text,fontWeight:'900',fontSize:13,marginTop:4},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:5},section:{color:colors.text,fontSize:16,fontWeight:'900'},link:{color:colors.accent,fontSize:11,fontWeight:'800'},overview:{flexDirection:'row',gap:8},overviewCard:{flex:1,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:16,padding:13,gap:5},overviewValue:{color:colors.text,fontSize:19,fontWeight:'900'},miniRow:{flexDirection:'row',justifyContent:'space-between',gap:8},miniName:{color:colors.text,fontSize:11,fontWeight:'700'},miniValue:{color:colors.text,fontSize:11,fontWeight:'800'},categoryCard:{borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:18,padding:15,gap:11},categoryRow:{gap:5},bar:{height:6,borderRadius:3,backgroundColor:colors.surface2,overflow:'hidden',marginTop:5},barFill:{height:'100%',backgroundColor:colors.accent,borderRadius:3},tx:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:16,padding:14,flexDirection:'row',alignItems:'center',gap:10},txCategory:{color:colors.text,fontWeight:'800'},txAmount:{fontWeight:'800'}})
