import { ChangeEvent, useRef, useState } from 'react'
import { AlertTriangle, Download, Upload } from 'lucide-react'
import { loadData, saveData, SpenzaData } from '../lib/db'

type BackupFile={app:'Spenza';version:1;exportedAt:string;data:SpenzaData}
type Props={onImported?:(data:SpenzaData)=>void}
type ValidationResult={valid:true;backup:BackupFile}|{valid:false;reason:string}
function isValidDate(value:unknown){return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T12:00:00`))}
function validateBackup(value:unknown):ValidationResult{
 if(!value||typeof value!=='object')return{valid:false,reason:'The JSON root must be an object.'}
 const backup=value as Partial<BackupFile>
 if(backup.app!=='Spenza')return{valid:false,reason:'This file is not marked as a Spenza backup.'}
 if(backup.version!==1)return{valid:false,reason:`Unsupported backup version: ${String(backup.version??'missing')}.`}
 const data=backup.data as Partial<SpenzaData>|undefined
 if(!data||typeof data!=='object')return{valid:false,reason:'The backup is missing its data section.'}
 if(!Array.isArray(data.wallets))return{valid:false,reason:'The backup wallets list is missing or invalid.'}
 if(!Array.isArray(data.transactions))return{valid:false,reason:'The backup transactions list is missing or invalid.'}
 if(!Array.isArray(data.categories))return{valid:false,reason:'The backup categories list is missing or invalid.'}
 const wallets=data.wallets as SpenzaData['wallets'];const transactions=data.transactions as SpenzaData['transactions'];const bills=Array.isArray(data.bills)?data.bills:[]
 for(let i=0;i<wallets.length;i++){const w=wallets[i];if(!w||typeof w.id!=='string'||!w.id)return{valid:false,reason:`Wallet ${i+1} has no valid ID.`};if(typeof w.name!=='string')return{valid:false,reason:`Wallet ${i+1} has an invalid name.`};if(w.currency!=='USD'&&w.currency!=='LBP')return{valid:false,reason:`Wallet “${w.name||i+1}” has unsupported currency “${String(w.currency)}”.`};if(!Number.isFinite(Number(w.openingBalance)))return{valid:false,reason:`Wallet “${w.name||i+1}” has an invalid opening balance.`}}
 const walletIds=new Set(wallets.map(w=>w.id));if(walletIds.size!==wallets.length)return{valid:false,reason:'The backup contains duplicate wallet IDs.'}
 for(let i=0;i<data.categories.length;i++){const c=data.categories[i];if(typeof c!=='string'||!c.trim())return{valid:false,reason:`Category ${i+1} is empty or invalid.`}}
 const txIds=new Set<string>()
 for(let i=0;i<transactions.length;i++){const t=transactions[i];const label=`Transaction ${i+1}${t&&typeof t==='object'&&'title'in t?` (“${String(t.title)}”)`:''}`;if(!t||typeof t.id!=='string'||!t.id)return{valid:false,reason:`${label} has no valid ID.`};if(txIds.has(t.id))return{valid:false,reason:`${label} has a duplicate ID.`};txIds.add(t.id);if(!['income','expense','transfer'].includes(t.type))return{valid:false,reason:`${label} has invalid type “${String(t.type)}”.`};if(typeof t.title!=='string')return{valid:false,reason:`${label} has an invalid description/title.`};if(typeof t.category!=='string')return{valid:false,reason:`${label} has an invalid category.`};if(!Number.isFinite(Number(t.amount))||Number(t.amount)<=0)return{valid:false,reason:`${label} has an invalid amount.`};if(!walletIds.has(t.walletId))return{valid:false,reason:`${label} references a wallet that does not exist in this backup.`};if(!isValidDate(t.date))return{valid:false,reason:`${label} has invalid date “${String(t.date)}”.`};if(t.type==='transfer'&&(!t.toWalletId||!walletIds.has(t.toWalletId)||t.toWalletId===t.walletId||!Number.isFinite(Number(t.exchangeRate))||Number(t.exchangeRate)<=0))return{valid:false,reason:`${label} has invalid transfer wallet/rate information.`}}
 const billIds=new Set<string>()
 for(let i=0;i<bills.length;i++){const b=bills[i];const label=`Bill ${i+1}${b&&typeof b==='object'&&'name'in b?` (“${String(b.name)}”)`:''}`;if(!b||typeof b.id!=='string'||!b.id)return{valid:false,reason:`${label} has no valid ID.`};if(billIds.has(b.id))return{valid:false,reason:`${label} has a duplicate ID.`};billIds.add(b.id);if(typeof b.name!=='string'||!b.name.trim())return{valid:false,reason:`${label} has an invalid name.`};if(!walletIds.has(b.walletId))return{valid:false,reason:`${label} references a wallet that does not exist.`};if(!Number.isFinite(Number(b.amount))||Number(b.amount)<=0)return{valid:false,reason:`${label} has an invalid amount.`};if(!isValidDate(b.dueDate))return{valid:false,reason:`${label} has invalid due date “${String(b.dueDate)}”.`};if(!['once','monthly','yearly'].includes(b.recurrence))return{valid:false,reason:`${label} has invalid recurrence “${String(b.recurrence)}”.`};if(![0,1,3,7].includes(b.reminderDays))return{valid:false,reason:`${label} has unsupported reminder days “${String(b.reminderDays)}”.`}}
 return{valid:true,backup:backup as BackupFile}
}
function prepareLocalRestore(data:SpenzaData):SpenzaData{return{...data,bills:data.bills||[],sync:{tombstones:[],pendingChanges:[],lastSyncAt:undefined}}}

export default function BackupManager({onImported}:Props){
 const inputRef=useRef<HTMLInputElement>(null)
 const [message,setMessage]=useState('')
 const [importing,setImporting]=useState(false)
 const [pendingBackup,setPendingBackup]=useState<BackupFile|null>(null)
 const exportBackup=async()=>{try{const data=await loadData();const backup:BackupFile={app:'Spenza',version:1,exportedAt:new Date().toISOString(),data};const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`spenza-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);setMessage('Backup exported successfully.')}catch(error){setMessage(`Could not export the backup: ${error instanceof Error?error.message:String(error)}`)}}
 const importBackup=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file||importing)return;try{setImporting(true);setMessage('Checking backup…');let parsed:unknown;try{parsed=JSON.parse(await file.text())}catch(error){setMessage(`Could not read this JSON file: ${error instanceof Error?error.message:String(error)}`);return}const validation=validateBackup(parsed);if(!validation.valid){setMessage(`Import blocked: ${validation.reason}`);return}setPendingBackup(validation.backup);setMessage('Backup is valid and ready to import.')}catch(error){console.error('Backup import validation failed',error);setMessage(`Could not inspect this backup: ${error instanceof Error?error.message:String(error)}`)}finally{setImporting(false)}}
 const confirmImport=async()=>{if(!pendingBackup||importing)return;try{setImporting(true);setMessage('Restoring backup locally…');const imported=prepareLocalRestore(pendingBackup.data);await saveData(imported);onImported?.(imported);setPendingBackup(null);setMessage(`Backup imported successfully: ${imported.wallets.length} wallet${imported.wallets.length===1?'':'s'} and ${imported.transactions.length} transaction${imported.transactions.length===1?'':'s'}. No cloud sync was started.`)}catch(error){console.error('Backup import failed',error);setMessage(`Import failed while saving to this device: ${error instanceof Error?error.message:String(error)}. Your previous data was left available.`)}finally{setImporting(false)}}
 return <><section className="backup-settings"><div><h2>Backup & restore</h2><p>Export your local Spenza data or restore a backup on this device.</p></div><div className="backup-settings-actions"><button onClick={exportBackup} disabled={importing}><Download size={17}/><span><b>Export backup</b><small>Download JSON backup</small></span></button><button onClick={()=>inputRef.current?.click()} disabled={importing}><Upload size={17}/><span><b>{importing?'Importing…':'Import backup'}</b><small>{importing?'Checking safely':'Restore JSON backup'}</small></span></button></div><input ref={inputRef} type="file" accept="application/json,.json" hidden onChange={importBackup}/>{message&&<div className="backup-message">{message}</div>}</section>{pendingBackup&&<div className="dialogOverlay" onClick={()=>{if(!importing)setPendingBackup(null)}}><div className="dialogCard" role="dialog" aria-modal="true" aria-labelledby="import-backup-title" onClick={e=>e.stopPropagation()}><div className="dialogIcon dangerIcon"><AlertTriangle/></div><h2 id="import-backup-title">Import backup?</h2><p>This will replace the data currently stored on this device with <b>{pendingBackup.data.wallets.length}</b> wallet{pendingBackup.data.wallets.length===1?'':'s'} and <b>{pendingBackup.data.transactions.length}</b> transaction{pendingBackup.data.transactions.length===1?'':'s'}. It will restore locally only and will not start cloud sync.</p><div className="dialogActions"><button className="dialogCancel" disabled={importing} onClick={()=>setPendingBackup(null)}>Cancel</button><button className="dialogConfirm" disabled={importing} onClick={confirmImport}>{importing?'Importing…':'Import backup'}</button></div></div></div>}</>
}
