import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowDownLeft, ArrowLeftRight, ArrowUpRight, BarChart3, Bell, CalendarClock, Check, ChevronLeft, ChevronRight, CreditCard, Home, Pencil, Plus, Settings, Trash2, WalletCards, X } from 'lucide-react'
import ReceiptScanner from './components/ReceiptScanner'
import NotePhotoPicker from './components/NotePhotoPicker'
import BackupManager from './components/BackupManager'
import ThemeControl from './components/ThemeControl'
import BillsManager from './components/BillsManager'
import SecuritySettings from './components/SecuritySettings'
import AppLockGate from './components/AppLockGate'
import NotificationCenter, { NotificationBell } from './components/NotificationCenter'
import { Currency, defaultData, loadData, saveData, SpenzaData, Transaction, TransactionType, uid, Wallet } from './lib/db'

const money=(n:number,c:Currency|'USD'='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:c==='LBP'?0:2}).format(n)
const today=()=>new Date().toISOString().slice(0,10)
type Dialog={title:string;message:string;kind?:'danger'|'info';confirmLabel?:string;onConfirm?:()=>void}
type WalletForm={id?:string;name:string;currency:Currency;openingBalance:string;originalCurrency?:Currency}
type ReceiptSource={amount:number;currency?:Currency}
type InsightPeriod='daily'|'monthly'|'yearly'
type HomePeriod=InsightPeriod|'custom'
const palette=['#22d3ae','#7650ea','#2d94ee','#17a9a5','#a150e3']

export default function App(){
 const [data,setData]=useState<SpenzaData>(defaultData)
 const [ready,setReady]=useState(false)
 const [tab,setTab]=useState('Home')
 const [activityWalletId,setActivityWalletId]=useState<string|null>(null)
 const [insightWalletId,setInsightWalletId]=useState('')
 const [insightCategory,setInsightCategory]=useState('all')
 const [insightPeriod,setInsightPeriod]=useState<InsightPeriod>('monthly')
 const [insightDate,setInsightDate]=useState(today())
 const [homeWalletId,setHomeWalletId]=useState(()=>localStorage.getItem('spenza-home-wallet-id')||'')
 const [homePeriod,setHomePeriod]=useState<HomePeriod>('monthly')
 const [homeDate,setHomeDate]=useState(today())
 const [rateInput,setRateInput]=useState(String(defaultData.usdToLbpRate||89500))
 const [open,setOpen]=useState(false)
 const [editing,setEditing]=useState<string|null>(null)
 const [dialog,setDialog]=useState<Dialog|null>(null)
 const [dialogBusy,setDialogBusy]=useState(false)
 const [walletForm,setWalletForm]=useState<WalletForm|null>(null)
 const [receiptSource,setReceiptSource]=useState<ReceiptSource|null>(null)
 const [type,setType]=useState<TransactionType>('expense')
 const [title,setTitle]=useState('')
 const [amount,setAmount]=useState('')
 const [category,setCategory]=useState('Food')
 const [walletId,setWalletId]=useState('')
 const [toWalletId,setToWalletId]=useState('')
 const [date,setDate]=useState(today())
 const [note,setNote]=useState('')
 const [noteImages,setNoteImages]=useState<string[]>([])
 const [notificationsOpen,setNotificationsOpen]=useState(false)
 useEffect(()=>{loadData().then(d=>{setData(d);setRateInput(String(d.usdToLbpRate||89500));setReady(true)}).catch(()=>setReady(true))},[])
 useEffect(()=>{if(ready)saveData(data)},[data,ready])
 useEffect(()=>{if(!insightWalletId&&data.wallets[0])setInsightWalletId(data.wallets[0].id);if(insightWalletId&&!data.wallets.some(w=>w.id===insightWalletId))setInsightWalletId(data.wallets[0]?.id||'')},[data.wallets,insightWalletId])
 useEffect(()=>{if(!homeWalletId&&data.wallets[0]){setHomeWalletId(data.wallets[0].id);return}if(homeWalletId&&!data.wallets.some(w=>w.id===homeWalletId)){const fallback=data.wallets[0]?.id||'';setHomeWalletId(fallback);if(fallback)localStorage.setItem('spenza-home-wallet-id',fallback);else localStorage.removeItem('spenza-home-wallet-id')}},[data.wallets,homeWalletId])
 useEffect(()=>{if(homeWalletId)localStorage.setItem('spenza-home-wallet-id',homeWalletId);else localStorage.removeItem('spenza-home-wallet-id')},[homeWalletId])
 const rate=data.usdToLbpRate||89500
 const convert=(value:number,from:Currency,to:Currency)=>from===to?value:from==='USD'?value*rate:value/rate
 const normalize=(value:number,currency:Currency)=>currency==='LBP'?Math.round(value):Math.round(value*100)/100
 const pairRate=(from:Currency,to:Currency)=>from===to?1:from==='USD'?rate:1/rate
 const walletBalance=(id:string)=>{const w=data.wallets.find(x=>x.id===id);if(!w)return 0;return data.transactions.reduce((b,t)=>{if(t.type==='income'&&t.walletId===id)return b+t.amount;if(t.type==='expense'&&t.walletId===id)return b-t.amount;if(t.type==='transfer'){if(t.walletId===id)return b-t.amount;if(t.toWalletId===id)return b+(t.exchangeRate?t.amount*t.exchangeRate:t.amount)}return b},w.openingBalance)}
 const walletUsed=(id:string)=>data.transactions.some(t=>t.walletId===id||t.toWalletId===id)
 const resetForm=()=>{setEditing(null);setType('expense');setTitle('');setAmount('');setCategory(data.categories[0]||'Other');setWalletId(data.wallets[0]?.id||'');setToWalletId(data.wallets[1]?.id||data.wallets[0]?.id||'');setDate(today());setNote('');setNoteImages([]);setReceiptSource(null)}
 const showAdd=()=>{resetForm();setOpen(true)}
 const edit=(t:Transaction)=>{setEditing(t.id);setType(t.type);setTitle(t.title);setAmount(String(t.amount));setCategory(t.category);setWalletId(t.walletId);setToWalletId(t.toWalletId||'');setDate(t.date);setNote(t.note||'');setNoteImages(t.noteImages||[]);setReceiptSource(null);setOpen(true)}
 const applyReceiptAmount=(source:ReceiptSource,targetWalletId:string)=>{const wallet=data.wallets.find(w=>w.id===targetWalletId);if(!wallet||!source.currency){setAmount(String(source.amount));return}const converted=convert(source.amount,source.currency,wallet.currency);setAmount(wallet.currency==='LBP'?String(Math.round(converted)):converted.toFixed(2))}
 useEffect(()=>{if(receiptSource)applyReceiptAmount(receiptSource,walletId)},[walletId,data.usdToLbpRate])
 const handleReceipt=(result:{amount:number;currency?:Currency;merchant?:string;rawText:string})=>{setType('expense');const source={amount:result.amount,currency:result.currency};setReceiptSource(source);applyReceiptAmount(source,walletId);setTitle('');setNote(result.currency?`Receipt scanned in ${result.currency}`:'Added from scanned receipt')}
 const transferRate=()=>{const from=data.wallets.find(w=>w.id===walletId);const to=data.wallets.find(w=>w.id===toWalletId);if(!from||!to)return 1;return pairRate(from.currency,to.currency)}
 const addCategory=()=>{const raw=window.prompt('New category name');const name=raw?.trim();if(!name)return;const existing=data.categories.find(c=>c.toLowerCase()===name.toLowerCase());if(existing){setCategory(existing);return}setData(d=>({...d,categories:[...d.categories,name]}));setCategory(name)}
 const submit=()=>{const n=Number(amount);if(!n||n<=0)return;if(type!=='expense'&&!title.trim())return;if(!walletId){setDialog({title:'Create a wallet first',message:'Add at least one wallet before saving a transaction.',kind:'info'});return}if(type==='transfer'&&!toWalletId){setDialog({title:'Choose a destination wallet',message:'Transfers need both a source wallet and a destination wallet.',kind:'info'});return}const now=new Date().toISOString();const old=data.transactions.find(t=>t.id===editing);const displayTitle=title.trim()||(type==='expense'?category:'Transaction');const tx:Transaction={id:editing||uid(),type,title:displayTitle,category:type==='transfer'?'Transfer':category,amount:n,walletId,toWalletId:type==='transfer'?toWalletId:undefined,exchangeRate:type==='transfer'?transferRate():undefined,date,note:note.trim()||undefined,noteImages:noteImages.length?noteImages:undefined,createdAt:old?.createdAt||now,updatedAt:now};setData(d=>({...d,transactions:editing?d.transactions.map(x=>x.id===editing?tx:x):[tx,...d.transactions]}));setOpen(false);resetForm()}
 const remove=(id:string)=>{const tx=data.transactions.find(t=>t.id===id);setDialog({title:'Delete transaction?',message:`${tx?.title||'This transaction'} will be permanently removed from your activity and balances.`,kind:'danger',confirmLabel:'Delete',onConfirm:()=>setData(d=>({...d,transactions:d.transactions.filter(t=>t.id!==id)}))})}
 const addWallet=()=>setWalletForm({name:'',currency:'USD',openingBalance:'0',originalCurrency:'USD'})
 const editWallet=(w:Wallet)=>setWalletForm({id:w.id,name:w.name,currency:w.currency,openingBalance:String(w.openingBalance),originalCurrency:w.currency})
 const changeWalletCurrency=(next:Currency)=>{if(!walletForm||walletForm.currency===next)return;const current=walletForm.currency;const opening=Number(walletForm.openingBalance);setWalletForm({...walletForm,currency:next,openingBalance:Number.isNaN(opening)?walletForm.openingBalance:String(normalize(convert(opening,current,next),next))})}
 const saveWallet=()=>{if(!walletForm)return;const name=walletForm.name.trim();const opening=Number(walletForm.openingBalance);if(!name||Number.isNaN(opening))return;if(walletForm.id){const existing=data.wallets.find(w=>w.id===walletForm.id);if(!existing)return;const newCurrency=walletForm.currency;const oldCurrency=existing.currency;const now=new Date().toISOString();setData(d=>{const currencyFor=(id?:string)=>{if(!id)return undefined;if(id===existing.id)return newCurrency;return d.wallets.find(w=>w.id===id)?.currency};const transactions=d.transactions.map(t=>{if(t.type!=='transfer'){if(t.walletId!==existing.id)return t;return {...t,amount:normalize(convert(t.amount,oldCurrency,newCurrency),newCurrency),updatedAt:now}}if(t.walletId!==existing.id&&t.toWalletId!==existing.id)return t;const sourceBefore=t.walletId===existing.id?oldCurrency:currencyFor(t.walletId)||oldCurrency;const sourceAfter=t.walletId===existing.id?newCurrency:sourceBefore;const destinationAfter=t.toWalletId===existing.id?newCurrency:(currencyFor(t.toWalletId)||sourceAfter);const convertedAmount=t.walletId===existing.id?normalize(convert(t.amount,oldCurrency,newCurrency),newCurrency):t.amount;return {...t,amount:convertedAmount,exchangeRate:pairRate(sourceAfter,destinationAfter),updatedAt:now}});return {...d,wallets:d.wallets.map(w=>w.id===existing.id?{...w,name,currency:newCurrency,openingBalance:opening}:w),transactions}})}else{const id=uid();setData(d=>({...d,wallets:[...d.wallets,{id,name,currency:walletForm.currency,openingBalance:opening}]}));if(!walletId)setWalletId(id)}setWalletForm(null)}
 const deleteWallet=(id:string)=>{const wallet=data.wallets.find(w=>w.id===id);if(!wallet)return;const related=data.transactions.filter(t=>t.walletId===id||t.toWalletId===id);const relatedBills=(data.bills||[]).filter(b=>b.walletId===id);const count=related.length;const billCount=relatedBills.length;setDialog({title:`Delete ${wallet.name}?`,message:`This account${count?` and ${count} related transaction${count===1?'':'s'}`:''}${billCount?` and ${billCount} related bill${billCount===1?'':'s'}`:''} will be permanently deleted. This cannot be undone.`,kind:'danger',confirmLabel:'Delete account',onConfirm:async()=>{try{const next:SpenzaData={...data,wallets:data.wallets.filter(w=>w.id!==id),transactions:data.transactions.filter(t=>t.walletId!==id&&t.toWalletId!==id),bills:(data.bills||[]).filter(b=>b.walletId!==id)};await saveData(next);setData(next);if(activityWalletId===id)setActivityWalletId(null);if(insightWalletId===id)setInsightWalletId('');if(homeWalletId===id)setHomeWalletId('');if(walletId===id)setWalletId('');if(toWalletId===id)setToWalletId('');setDialog({title:'Account deleted',message:`${wallet.name} and its related data were removed from this device.`,kind:'info'})}catch{setDialog({title:'Could not delete account',message:'Spenza could not save the account deletion to local storage. Please try again.',kind:'info'})}}})}
 const resetAll=()=>setDialog({title:'Reset Spenza?',message:'All local wallets and transactions will be permanently cleared. This cannot be undone.',kind:'danger',confirmLabel:'Reset data',onConfirm:()=>{setData(defaultData);setRateInput(String(defaultData.usdToLbpRate||89500))}})
 const confirmDialog=async()=>{const action=dialog?.onConfirm;if(!action||dialogBusy)return;setDialogBusy(true);try{await action();setDialog(current=>current?.onConfirm===action?null:current)}finally{setDialogBusy(false)}}
 const commitRate=()=>{const n=Number(rateInput);if(n>0){setData(d=>({...d,usdToLbpRate:n}));setRateInput(String(n))}else setRateInput(String(rate))}
 const openWalletActivity=(id:string)=>{setActivityWalletId(id);setTab('Activity')}
 const openAllActivity=()=>{setActivityWalletId(null);setTab('Activity')}
 const inInsightPeriod=(txDate:string)=>{if(insightPeriod==='daily')return txDate===insightDate;if(insightPeriod==='monthly')return txDate.slice(0,7)===insightDate.slice(0,7);return txDate.slice(0,4)===insightDate.slice(0,4)}
 const TxRow=({t}:{t:Transaction})=>{const w=data.wallets.find(x=>x.id===t.walletId);const sign=t.type==='income'?'+':t.type==='expense'?'-':'−';const photos=t.noteImages?.length||0;return <div className="tx"><div className={`txIcon ${t.type}`}>{t.type==='income'?<ArrowDownLeft/>:t.type==='transfer'?<ArrowLeftRight/>:<ArrowUpRight/>}</div><div className="txMain"><b>{t.title}</b><span>{t.category} · {w?.name||'No wallet'}{photos?` · 📷 ${photos}`:''}</span></div><div className="txAmount"><strong className={t.type==='income'?'positive':''}>{sign}{money(t.amount,w?.currency||'USD')}</strong><small>{t.date}</small></div><div className="txActions"><button onClick={()=>edit(t)}><Pencil/></button><button onClick={()=>remove(t.id)}><Trash2/></button></div></div>}
 const selectedWallet=data.wallets.find(w=>w.id===walletId)
 const activityWallet=activityWalletId?data.wallets.find(w=>w.id===activityWalletId):undefined
 const activityTransactions=activityWalletId?data.transactions.filter(t=>t.walletId===activityWalletId||t.toWalletId===activityWalletId):data.transactions
 const insightWallet=data.wallets.find(w=>w.id===insightWalletId)
 const insightTransactions=data.transactions.filter(t=>t.walletId===insightWalletId&&inInsightPeriod(t.date)&&(insightCategory==='all'||t.category===insightCategory))
 const insightExpenses=insightTransactions.filter(t=>t.type==='expense').reduce((sum,t)=>sum+t.amount,0)
 const insightIncome=insightTransactions.filter(t=>t.type==='income').reduce((sum,t)=>sum+t.amount,0)
 const insightTransfers=insightTransactions.filter(t=>t.type==='transfer').reduce((sum,t)=>sum+t.amount,0)
 const insightPeriodLabel=insightPeriod==='daily'?insightDate:insightPeriod==='monthly'?new Date(`${insightDate.slice(0,7)}-01T00:00:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'}):insightDate.slice(0,4)
 const conversionLabel=receiptSource?.currency&&selectedWallet&&receiptSource.currency!==selectedWallet.currency?`${money(receiptSource.amount,receiptSource.currency)} → ${money(Number(amount)||0,selectedWallet.currency)} at 1 USD = ${rate.toLocaleString()} LBP`:null
 const inHomePeriod=(txDate:string)=>{if(homePeriod==='daily'||homePeriod==='custom')return txDate===homeDate;if(homePeriod==='monthly')return txDate.slice(0,7)===homeDate.slice(0,7);return txDate.slice(0,4)===homeDate.slice(0,4)}
 const shiftHomePeriod=(direction:number)=>{const d=new Date(`${homeDate}T12:00:00`);if(homePeriod==='daily'||homePeriod==='custom')d.setDate(d.getDate()+direction);else if(homePeriod==='monthly')d.setMonth(d.getMonth()+direction);else d.setFullYear(d.getFullYear()+direction);setHomeDate(d.toISOString().slice(0,10))}
 const homePeriodLabel=homePeriod==='daily'||homePeriod==='custom'?new Date(`${homeDate}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):homePeriod==='monthly'?new Date(`${homeDate.slice(0,7)}-01T12:00:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'}):homeDate.slice(0,4)
 const homeWallet=data.wallets.find(w=>w.id===homeWalletId)||data.wallets[0]
 const homePeriodTx=homeWallet?data.transactions.filter(t=>(t.walletId===homeWallet.id||t.toWalletId===homeWallet.id)&&inHomePeriod(t.date)):[]
 const homeIncome=homePeriodTx.filter(t=>t.type==='income'&&t.walletId===homeWallet?.id).reduce((s,t)=>s+t.amount,0)
 const homeExpense=homePeriodTx.filter(t=>t.type==='expense'&&t.walletId===homeWallet?.id).reduce((s,t)=>s+t.amount,0)
 const homeTransferOut=homePeriodTx.filter(t=>t.type==='transfer'&&t.walletId===homeWallet?.id).reduce((s,t)=>s+t.amount,0)
 const homeTransferIn=homePeriodTx.filter(t=>t.type==='transfer'&&t.toWalletId===homeWallet?.id).reduce((s,t)=>s+(t.exchangeRate?t.amount*t.exchangeRate:t.amount),0)
 const homeNet=homeIncome-homeExpense-homeTransferOut+homeTransferIn
 const categoryTotals=data.categories.map(c=>({name:c,value:homePeriodTx.filter(t=>t.type==='expense'&&t.walletId===homeWallet?.id&&t.category===c).reduce((s,t)=>s+t.amount,0)})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value)
 const categoryTotal=categoryTotals.reduce((s,x)=>s+x.value,0)
 let running=0
 const gradientParts=categoryTotals.slice(0,5).map((x,i)=>{const start=categoryTotal?running/categoryTotal*100:0;running+=x.value;const end=categoryTotal?running/categoryTotal*100:0;return `${palette[i%palette.length]} ${start}% ${end}%`})
 const donutBackground=gradientParts.length?`conic-gradient(${gradientParts.join(',')})`:'conic-gradient(var(--surface3) 0 100%)'
 const activityGroups=activityTransactions.reduce<Record<string,Transaction[]>>((acc,t)=>{(acc[t.date]??=[]).push(t);return acc},{})
 return <div className="shell"><main className="phone reference-layout">
  {tab==='Home'&&<section className="homeScreen">
   <header className="refHeader"><div><span className="eyebrow">SPENZA</span><h1>Good Morning! 👋</h1></div><NotificationBell data={data} onClick={()=>setNotificationsOpen(true)}/></header>
   <div className="filters refFilters periodFilters homePeriodFilters">{(['daily','monthly','yearly'] as InsightPeriod[]).map(p=><button key={p} className={homePeriod===p?'selected':''} onClick={()=>setHomePeriod(p)}>{p}</button>)}<label className={`customDateButton ${homePeriod==='custom'?'selected':''}`}>custom<input id="home-custom-date" className="homeCustomDateInput" type="date" value={homeDate} onClick={()=>setHomePeriod('custom')} onChange={e=>{if(e.target.value)setHomeDate(e.target.value);setHomePeriod('custom')}} aria-label="Choose custom date"/></label></div>
   {data.wallets.length&&<div className="insightSelectors homeAccountSelector"><label>Account<select value={homeWallet?.id||''} onChange={e=>setHomeWalletId(e.target.value)}>{data.wallets.map(w=><option key={w.id} value={w.id}>{w.name} ({w.currency})</option>)}</select></label></div>}
   <section className="monthCard"><button onClick={()=>shiftHomePeriod(-1)} aria-label="Previous period"><ChevronLeft/></button><div><b>{homePeriodLabel}</b><span>{homeWallet?`${homeWallet.name} · ${homePeriod} net`:`${homePeriod} overview`}</span><strong>{homeWallet?money(homeNet,homeWallet.currency):'—'}</strong></div><button onClick={()=>shiftHomePeriod(1)} aria-label="Next period"><ChevronRight/></button></section>
   <div className="refSectionHead"><h2>Accounts</h2><button onClick={()=>setTab('Wallets')}>See All</button></div>
   {data.wallets.length?<div className="accountRail">{data.wallets.slice(0,4).map((w,i)=><button className={`accountTile accountTone${i%4}${homeWallet?.id===w.id?' selectedAccount':''}`} key={w.id} onClick={()=>setHomeWalletId(w.id)}><div><b>{w.name}</b><span>{w.currency}</span></div><strong>{money(walletBalance(w.id),w.currency)}</strong></button>)}</div>:<button className="emptyWalletCta" onClick={addWallet}><WalletCards/><span><b>Create your first wallet</b><small>Add cash, bank, or card balances before recording expenses.</small></span></button>}
   <div className="refSectionHead"><h2>{homePeriodLabel} Overview</h2><button onClick={()=>{if(homeWallet)setInsightWalletId(homeWallet.id);setInsightPeriod(homePeriod==='custom'?'daily':homePeriod);setInsightDate(homeDate);setTab('Insights')}}>See All</button></div>
   <div className="overviewGrid"><article className="overviewIncome"><span>Total Income</span><strong>{homeWallet?money(homeIncome,homeWallet.currency):'—'}</strong><small>{homeWallet?`Expenses ${money(homeExpense,homeWallet.currency)}`:'Create a wallet first'}</small></article><article><span>Top Categories</span>{categoryTotals.slice(0,3).length?categoryTotals.slice(0,3).map(x=><div className="miniCategory" key={x.name}><span>{x.name}</span><b>{money(x.value,homeWallet?.currency||'USD')}</b></div>):<small>No spending yet</small>}</article></div>
   <article className="categoryPanel"><div className="refSectionHead compact"><h2>Expenses by Category</h2></div><div className="categoryChart"><div className="donut" style={{background:donutBackground}}><i/></div><div className="legend">{categoryTotals.slice(0,5).map((x,i)=><div key={x.name}><span><i style={{background:palette[i%palette.length]}}/>{x.name}</span><b>{categoryTotal?Math.round(x.value/categoryTotal*100):0}%</b></div>)}{!categoryTotals.length&&<small>No expense data yet</small>}</div></div></article>
   <section className="activity homeActivity"><div className="refSectionHead"><h2>Recent Transactions</h2><button onClick={openAllActivity}>See All</button></div>{homePeriodTx.length?homePeriodTx.slice(0,4).map(t=><TxRow t={t} key={t.id}/>):<div className="empty compact">No transactions for this account and period.</div>}</section>
  </section>}
  {tab==='Activity'&&<section className="page refPage"><div className="centerPageHead"><h1>{activityWallet?.name||'Transactions'}</h1></div>{activityWallet&&<div className="accountSummary"><span>{activityWallet.currency} balance</span><strong>{money(walletBalance(activityWallet.id),activityWallet.currency)}</strong></div>}<div className="filters refFilters"><button className={!activityWalletId?'selected':''} onClick={()=>setActivityWalletId(null)}>All</button><button onClick={()=>{resetForm();setType('income');setOpen(true)}}>Income</button><button onClick={()=>{resetForm();setType('expense');setOpen(true)}}>Expense</button><button onClick={()=>{resetForm();setType('transfer');setOpen(true)}}>Transfer</button></div><div className="groupedTransactions">{Object.entries(activityGroups).map(([d,items])=><section key={d}><h3>{d===today()?'Today':new Date(`${d}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</h3>{items.map(t=><TxRow t={t} key={t.id}/>)}</section>)}{!activityTransactions.length&&<div className="empty">No transactions yet.</div>}</div></section>}
  {tab==='Wallets'&&<section className="page refPage"><div className="centerPageHead withAction"><h1>Accounts</h1><button className="iconAdd" onClick={addWallet}><Plus/></button></div>{data.wallets.length?<div className="walletGrid refWalletGrid">{data.wallets.map((w,i)=><article className={`accountTone${i%4}`} key={w.id}><div className="walletCardTop"><span>{w.currency}</span><div className="walletActions"><button className="walletEdit" onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();editWallet(w)}}><Pencil/></button><button className="walletDelete" onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();deleteWallet(w.id)}}><Trash2/></button></div></div><h2 onClick={()=>openWalletActivity(w.id)}>{w.name}</h2><strong onClick={()=>openWalletActivity(w.id)}>{money(walletBalance(w.id),w.currency)}</strong><small>Opening {money(w.openingBalance,w.currency)}</small></article>)}</div>:<div className="empty">No accounts yet.</div>}</section>}
  {tab==='Insights'&&<section className="page refPage"><div className="centerPageHead"><h1>Insights</h1></div>{data.wallets.length?<><div className="filters refFilters periodFilters">{(['daily','monthly','yearly'] as InsightPeriod[]).map(p=><button key={p} className={insightPeriod===p?'selected':''} onClick={()=>setInsightPeriod(p)}>{p}</button>)}</div><div className="insightNavigator"><ChevronLeft/><label><span>{insightPeriodLabel}</span><input type="date" value={insightDate} onChange={e=>setInsightDate(e.target.value)}/></label><ChevronRight/></div><div className="insightSelectors"><label>Account<select value={insightWalletId} onChange={e=>setInsightWalletId(e.target.value)}>{data.wallets.map(w=><option key={w.id} value={w.id}>{w.name} ({w.currency})</option>)}</select></label><label>Category<select value={insightCategory} onChange={e=>setInsightCategory(e.target.value)}><option value="all">All categories</option>{data.categories.map(c=><option key={c} value={c}>{c}</option>)}</select></label></div>{insightWallet&&<><div className="insightGrid refInsightGrid"><article><span>Expenses</span><strong>{money(insightExpenses,insightWallet.currency)}</strong></article><article><span>Income</span><strong>{money(insightIncome,insightWallet.currency)}</strong></article><article><span>Transactions</span><strong>{insightTransactions.length}</strong></article><article><span>Transfers Out</span><strong>{money(insightTransfers,insightWallet.currency)}</strong></article></div><article className="categoryPanel"><div className="refSectionHead compact"><h2>Expenses by Category</h2></div>{data.categories.map(c=>{const value=data.transactions.filter(t=>t.type==='expense'&&t.walletId===insightWallet.id&&inInsightPeriod(t.date)&&t.category===c&&(insightCategory==='all'||c===insightCategory)).reduce((sum,t)=>sum+t.amount,0);if(!value)return null;const pct=insightExpenses?Math.min(100,(value/insightExpenses)*100):0;return <div className="categoryRow" key={c}><span>{c}</span><div><i style={{width:`${pct}%`}}/></div><b>{money(value,insightWallet.currency)}</b></div>})}{!insightExpenses&&<div className="empty compact">No expense data for this period.</div>}</article></>}</>:<div className="empty">Create an account to see insights.</div>}</section>}
  {tab==='Bills'&&<BillsManager data={data} setData={setData}/>}
  {tab==='Settings'&&<section className="page refPage settingsPage"><div className="centerPageHead"><h1>Settings</h1></div><h3 className="settingsGroupTitle">Preferences</h3><section className="settingsList"><div className="settingsRow"><div><span>Currency Rate</span><small>USD / LBP conversion</small></div><label className="inlineRate">LBP <input type="number" inputMode="decimal" value={rateInput} onChange={e=>setRateInput(e.target.value)} onBlur={commitRate} onKeyDown={e=>{if(e.key==='Enter')(e.currentTarget as HTMLInputElement).blur()}} placeholder="89500"/></label></div><ThemeControl/><div className="settingsRow"><div><span>Data Storage</span><small>Stored locally on this device</small></div><b>Local Only</b></div></section><h3 className="settingsGroupTitle">Security</h3><section className="settingsList"><SecuritySettings data={data} setData={setData}/></section><h3 className="settingsGroupTitle">Backup & Restore</h3><BackupManager/><h3 className="settingsGroupTitle">Data</h3><button className="danger settingsDanger" onClick={resetAll}>Reset local data</button></section>}
  <nav>{[['Home',Home],['Activity',CreditCard],['Add',Plus],['Bills',CalendarClock],['Insights',BarChart3],['Settings',Settings]].map(([label,Icon]:any)=><button key={label} className={tab===label?'active':label==='Add'?'addNav':''} onClick={()=>{if(label==='Add')showAdd();else{if(label==='Activity')setActivityWalletId(null);setTab(label)}}}><Icon size={20}/><span>{label==='Activity'?'Transactions':label}</span></button>)}</nav>
  {open&&<div className="overlay" onClick={()=>setOpen(false)}><div className="sheet refSheet" onClick={e=>e.stopPropagation()}><div className="sheetTop"><div><span className="eyebrow">{editing?'EDIT':'ADD'}</span><h2>{editing?'Edit Transaction':'Add Transaction'}</h2></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div><div className="typeTabs refTypeTabs">{(['expense','income','transfer'] as TransactionType[]).map(v=><button className={type===v?'selected':''} onClick={()=>{setType(v);if(v!=='expense')setReceiptSource(null)}} key={v}>{v}</button>)}</div>{type==='expense'&&<ReceiptScanner onResult={handleReceipt}/>}<label>Amount{selectedWallet&&<small className="fieldHint">Saved in {selectedWallet.currency}</small>}<input className="amountInput" value={amount} onChange={e=>setAmount(e.target.value)} type="number" inputMode="decimal" placeholder="$ 0.00"/></label>{conversionLabel&&<div className="conversionNotice"><b>Converted receipt total</b><span>{conversionLabel}</span></div>}<label>Description {type==='expense'&&<small className="fieldHint">Optional</small>}<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={type==='income'?'Salary, refund...':type==='transfer'?'Move money...':'Optional description'}/></label><label>Category<div className="categoryControl"><select value={category} onChange={e=>setCategory(e.target.value)} disabled={type==='transfer'}>{type==='transfer'?<option>Transfer</option>:data.categories.map(c=><option key={c}>{c}</option>)}</select>{type!=='transfer'&&<button type="button" onClick={addCategory}><Plus size={15}/></button>}</div></label><label>Account<select value={walletId} onChange={e=>setWalletId(e.target.value)}><option value="">Select Account</option>{data.wallets.map(w=><option value={w.id} key={w.id}>{w.name} ({w.currency})</option>)}</select></label>{type==='transfer'&&<label>To Account<select value={toWalletId} onChange={e=>setToWalletId(e.target.value)}><option value="">Select Account</option>{data.wallets.filter(w=>w.id!==walletId).map(w=><option value={w.id} key={w.id}>{w.name} ({w.currency})</option>)}</select></label>}<label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a note (optional)"/></label><div className="noteAttachmentLabel">Photos</div><NotePhotoPicker images={noteImages} onChange={setNoteImages}/><button className="primary" onClick={submit}>{editing?'Save Changes':'Save Transaction'}</button></div></div>}
  {walletForm&&<div className="overlay" onClick={()=>setWalletForm(null)}><div className="sheet walletSheet refSheet" onClick={e=>e.stopPropagation()}><div className="sheetTop"><div><span className="eyebrow">{walletForm.id?'EDIT':'NEW'} ACCOUNT</span><h2>{walletForm.id?'Edit Account':'Add Account'}</h2></div><button className="close" onClick={()=>setWalletForm(null)}><X/></button></div><label>Account name<input value={walletForm.name} onChange={e=>setWalletForm({...walletForm,name:e.target.value})} placeholder="e.g. Main account" autoFocus/></label><label>Currency<select value={walletForm.currency} onChange={e=>changeWalletCurrency(e.target.value as Currency)}><option value="USD">USD — US Dollar</option><option value="LBP">LBP — Lebanese Pound</option></select></label><label>Opening balance<input type="number" inputMode="decimal" value={walletForm.openingBalance} onChange={e=>setWalletForm({...walletForm,openingBalance:e.target.value})}/></label>{walletForm.id&&walletForm.originalCurrency&&walletForm.originalCurrency!==walletForm.currency&&<div className="conversionNotice"><b>Currency conversion</b><span>Existing wallet history will be converted from {walletForm.originalCurrency} to {walletForm.currency} using 1 USD = {rate.toLocaleString()} LBP.</span></div>}<button className="primary" onClick={saveWallet}>{walletForm.id?'Save Account':'Create Account'}</button></div></div>}
  <NotificationCenter data={data} setData={setData} open={notificationsOpen} onClose={()=>setNotificationsOpen(false)}/>
  <AppLockGate data={data}/>
  {dialog&&<div className="dialogOverlay" onClick={()=>{if(!dialogBusy)setDialog(null)}}><div className="dialogCard" onClick={e=>e.stopPropagation()}><div className={`dialogIcon ${dialog.kind==='danger'?'dangerIcon':'infoIcon'}`}>{dialog.kind==='danger'?<AlertTriangle/>:<Check/>}</div><h2>{dialogBusy?'Deleting…':dialog.title}</h2><p>{dialog.message}</p><div className="dialogActions"><button className="dialogCancel" disabled={dialogBusy} onClick={()=>setDialog(null)}>{dialog.onConfirm?'Cancel':'Got it'}</button>{dialog.onConfirm&&<button className="dialogConfirm" disabled={dialogBusy} onClick={confirmDialog}>{dialogBusy?'Deleting…':dialog.confirmLabel||'Confirm'}</button>}</div></div></div>}
 </main></div>
}
