import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowDownLeft, ArrowLeftRight, ArrowUpRight, BarChart3, Check, CreditCard, Home, Pencil, Plus, Settings, Trash2, WalletCards, X } from 'lucide-react'
import ReceiptScanner from './components/ReceiptScanner'
import { defaultData, loadData, saveData, SpenzaData, Transaction, TransactionType, uid, Wallet } from './lib/db'

const money=(n:number,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:c==='LBP'?0:2}).format(n)
const today=()=>new Date().toISOString().slice(0,10)
type Dialog={title:string;message:string;kind?:'danger'|'info';confirmLabel?:string;onConfirm?:()=>void}
type WalletForm={id?:string;name:string;currency:'USD'|'LBP';openingBalance:string}

export default function App(){
 const [data,setData]=useState<SpenzaData>(defaultData); const [ready,setReady]=useState(false); const [tab,setTab]=useState('Home'); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<string|null>(null); const [dialog,setDialog]=useState<Dialog|null>(null); const [walletForm,setWalletForm]=useState<WalletForm|null>(null)
 const [type,setType]=useState<TransactionType>('expense'); const [title,setTitle]=useState(''); const [amount,setAmount]=useState(''); const [category,setCategory]=useState('Food'); const [walletId,setWalletId]=useState(''); const [toWalletId,setToWalletId]=useState(''); const [date,setDate]=useState(today()); const [note,setNote]=useState('')
 useEffect(()=>{loadData().then(d=>{setData(d);setReady(true)}).catch(()=>setReady(true))},[])
 useEffect(()=>{if(ready)saveData(data)},[data,ready])
 const walletBalance=(id:string)=>{const w=data.wallets.find(x=>x.id===id); if(!w)return 0; return data.transactions.reduce((b,t)=>{if(t.type==='income'&&t.walletId===id)return b+t.amount;if(t.type==='expense'&&t.walletId===id)return b-t.amount;if(t.type==='transfer'){if(t.walletId===id)return b-t.amount;if(t.toWalletId===id)return b+(t.exchangeRate?t.amount*t.exchangeRate:t.amount)}return b},w.openingBalance)}
 const walletUsed=(id:string)=>data.transactions.some(t=>t.walletId===id||t.toWalletId===id)
 const usdWallet=data.wallets.find(w=>w.currency==='USD'); const lbpWallet=data.wallets.find(w=>w.currency==='LBP'); const usd=usdWallet?walletBalance(usdWallet.id):0; const lbp=lbpWallet?walletBalance(lbpWallet.id):0; const totalUsd=usd+lbp/89500
 const spent=useMemo(()=>data.transactions.filter(t=>t.type==='expense').reduce((a,t)=>a+(data.wallets.find(w=>w.id===t.walletId)?.currency==='LBP'?t.amount/89500:t.amount),0),[data]); const income=useMemo(()=>data.transactions.filter(t=>t.type==='income').reduce((a,t)=>a+(data.wallets.find(w=>w.id===t.walletId)?.currency==='LBP'?t.amount/89500:t.amount),0),[data])
 const resetForm=()=>{setEditing(null);setType('expense');setTitle('');setAmount('');setCategory('Food');setWalletId(data.wallets[0]?.id||'');setToWalletId(data.wallets[1]?.id||data.wallets[0]?.id||'');setDate(today());setNote('')}
 const showAdd=()=>{resetForm();setOpen(true)}
 const edit=(t:Transaction)=>{setEditing(t.id);setType(t.type);setTitle(t.title);setAmount(String(t.amount));setCategory(t.category);setWalletId(t.walletId);setToWalletId(t.toWalletId||data.wallets[1]?.id||'');setDate(t.date);setNote(t.note||'');setOpen(true)}
 const handleReceipt=(result:{amount:number;merchant?:string;rawText:string})=>{setType('expense');setAmount(String(result.amount));if(result.merchant&&!title.trim())setTitle(result.merchant);setNote(n=>n||'Added from scanned receipt')}
 const submit=()=>{const n=Number(amount);if(!title.trim()||!n||n<=0)return;if(!walletId){setDialog({title:'Create a wallet first',message:'Add at least one wallet before saving a transaction.',kind:'info'});return}if(type==='transfer'&&!toWalletId){setDialog({title:'Choose a destination wallet',message:'Transfers need both a source wallet and a destination wallet.',kind:'info'});return}const now=new Date().toISOString();const old=data.transactions.find(t=>t.id===editing);const tx:Transaction={id:editing||uid(),type,title:title.trim(),category:type==='transfer'?'Transfer':category,amount:n,walletId,toWalletId:type==='transfer'?toWalletId:undefined,date,note:note.trim()||undefined,createdAt:old?.createdAt||now,updatedAt:now};setData(d=>({...d,transactions:editing?d.transactions.map(x=>x.id===editing?tx:x):[tx,...d.transactions]}));setOpen(false);resetForm()}
 const remove=(id:string)=>{const tx=data.transactions.find(t=>t.id===id);setDialog({title:'Delete transaction?',message:`${tx?.title||'This transaction'} will be permanently removed from your activity and balances.`,kind:'danger',confirmLabel:'Delete',onConfirm:()=>setData(d=>({...d,transactions:d.transactions.filter(t=>t.id!==id)}))})}
 const addWallet=()=>setWalletForm({name:'',currency:'USD',openingBalance:'0'})
 const editWallet=(w:Wallet)=>setWalletForm({id:w.id,name:w.name,currency:w.currency,openingBalance:String(w.openingBalance)})
 const saveWallet=()=>{if(!walletForm)return;const name=walletForm.name.trim();const opening=Number(walletForm.openingBalance);if(!name||Number.isNaN(opening))return;if(walletForm.id){const existing=data.wallets.find(w=>w.id===walletForm.id);if(!existing)return;const currency=walletUsed(existing.id)?existing.currency:walletForm.currency;setData(d=>({...d,wallets:d.wallets.map(w=>w.id===existing.id?{...w,name,currency,openingBalance:opening}:w)}))}else{const id=uid();setData(d=>({...d,wallets:[...d.wallets,{id,name,currency:walletForm.currency,openingBalance:opening}]}));if(!walletId)setWalletId(id)}setWalletForm(null)}
 const deleteWallet=(id:string)=>{const wallet=data.wallets.find(w=>w.id===id);if(!wallet)return;if(walletUsed(id)){setDialog({title:'Wallet is in use',message:'This wallet has transaction history. Reassign or delete those transactions before removing the wallet.',kind:'info'});return}setDialog({title:`Delete ${wallet.name}?`,message:'This wallet will be permanently removed from Spenza. This action cannot be undone.',kind:'danger',confirmLabel:'Delete wallet',onConfirm:()=>setData(d=>({...d,wallets:d.wallets.filter(w=>w.id!==id)}))})}
 const resetAll=()=>setDialog({title:'Reset Spenza?',message:'All local wallets and transactions will be permanently cleared. This cannot be undone.',kind:'danger',confirmLabel:'Reset data',onConfirm:()=>setData(defaultData)})
 const confirmDialog=()=>{dialog?.onConfirm?.();setDialog(null)}
 const TxRow=({t}: {t:Transaction})=>{const w=data.wallets.find(x=>x.id===t.walletId);const sign=t.type==='income'?'+':t.type==='expense'?'-':'→';return <div className="tx"><div className={`txIcon ${t.type}`}>{t.type==='income'?<ArrowDownLeft/>:t.type==='transfer'?<ArrowLeftRight/>:<ArrowUpRight/>}</div><div className="txMain"><b>{t.title}</b><span>{t.category} · {w?.name||'No wallet'} · {t.date}</span></div><strong className={t.type==='income'?'positive':''}>{sign}{money(t.amount,w?.currency)}</strong><div className="txActions"><button onClick={()=>edit(t)}><Pencil/></button><button onClick={()=>remove(t.id)}><Trash2/></button></div></div>}
 return <div className="shell"><main className="phone">
  {tab==='Home'&&<><header><div><span className="eyebrow">SPENZA · LOCAL MODE</span><h1>My finances</h1></div><button className="round" onClick={()=>setTab('Wallets')}><WalletCards size={19}/></button></header><section className="hero"><div className="heroTop"><span>Total available</span><span className="pill">● Offline ready</span></div><strong>{money(totalUsd)}</strong><div className="heroStats"><div><small>Income</small><b>+{money(income)}</b></div><div><small>Expenses</small><b>-{money(spent)}</b></div></div></section><section className="quick"><button onClick={showAdd}><i><Plus/></i><span>Add</span></button><button onClick={()=>setTab('Wallets')}><i><WalletCards/></i><span>Wallets</span></button><button onClick={()=>setTab('Activity')}><i><CreditCard/></i><span>Activity</span></button><button onClick={()=>setTab('Insights')}><i><BarChart3/></i><span>Insights</span></button></section>{data.wallets.length?<section className="walletStrip">{data.wallets.slice(0,2).map(w=><div key={w.id}><span>{w.name}</span><b>{money(walletBalance(w.id),w.currency)}</b></div>)}</section>:<button className="emptyWalletCta" onClick={addWallet}><WalletCards/><span><b>Create your first wallet</b><small>Add cash, bank, or card balances before recording expenses.</small></span></button>}<section className="activity"><div className="sectionHead"><h2>Recent activity</h2><button onClick={()=>setTab('Activity')}>All</button></div>{data.transactions.length?data.transactions.slice(0,5).map(t=><TxRow t={t} key={t.id}/>):<div className="empty compact">No transactions yet.</div>}</section></>}
  {tab==='Activity'&&<section className="page"><div className="pageHead"><div><span className="eyebrow">TRANSACTIONS</span><h1>Activity</h1></div><button className="primarySmall" onClick={showAdd}><Plus/> Add</button></div><div className="filters"><button className="selected">All</button><button onClick={()=>{resetForm();setType('expense');setOpen(true)}}>Expense</button><button onClick={()=>{resetForm();setType('income');setOpen(true)}}>Income</button><button onClick={()=>{resetForm();setType('transfer');setOpen(true)}}>Transfer</button></div>{data.transactions.length?data.transactions.map(t=><TxRow t={t} key={t.id}/>):<div className="empty">No transactions yet.</div>}</section>}
  {tab==='Wallets'&&<section className="page"><div className="pageHead"><div><span className="eyebrow">YOUR MONEY</span><h1>Wallets</h1></div><button className="primarySmall" onClick={addWallet}><Plus/> Wallet</button></div>{data.wallets.length?<div className="walletGrid">{data.wallets.map(w=><article key={w.id}><div className="walletCardTop"><span>{w.currency}</span><div className="walletActions"><button className="walletEdit" onClick={()=>editWallet(w)} aria-label={`Edit ${w.name}`}><Pencil/></button><button className="walletDelete" onClick={()=>deleteWallet(w.id)} aria-label={`Delete ${w.name}`}><Trash2/></button></div></div><h2>{w.name}</h2><strong>{money(walletBalance(w.id),w.currency)}</strong><small>Opening {money(w.openingBalance,w.currency)}</small></article>)}</div>:<div className="empty">No wallets yet. Create one to start tracking money.</div>}</section>}
  {tab==='Insights'&&<section className="page"><span className="eyebrow">OVERVIEW</span><h1>Insights</h1><div className="insightGrid"><article><span>Total expenses</span><strong>{money(spent)}</strong></article><article><span>Total income</span><strong>{money(income)}</strong></article><article><span>Transactions</span><strong>{data.transactions.length}</strong></article></div><h2 className="subTitle">Spending by category</h2>{data.categories.map(c=>{const v=data.transactions.filter(t=>t.type==='expense'&&t.category===c).reduce((a,t)=>a+t.amount,0);if(!v)return null;return <div className="categoryRow" key={c}><span>{c}</span><div><i style={{width:`${Math.min(100,(v/Math.max(spent,1))*100)}%`}}/></div><b>{money(v)}</b></div>})}</section>}
  {tab==='Settings'&&<section className="page"><span className="eyebrow">SPENZA</span><h1>Settings</h1><div className="manage"><div><h2>Data storage</h2><p>Your transactions and receipt scans are processed locally in this browser. Supabase cloud sync comes next.</p></div></div><button className="danger" onClick={resetAll}>Reset local data</button></section>}
  <nav>{[['Home',Home],['Activity',CreditCard],['Add',Plus],['Insights',BarChart3],['Settings',Settings]].map(([label,Icon]:any)=><button key={label} className={tab===label?'active':label==='Add'?'addNav':''} onClick={()=>label==='Add'?showAdd():setTab(label)}><Icon size={20}/><span>{label}</span></button>)}</nav>
  {open&&<div className="overlay" onClick={()=>setOpen(false)}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheetTop"><div><span className="eyebrow">{editing?'EDIT':'NEW'} TRANSACTION</span><h2>{editing?'Edit transaction':'Add transaction'}</h2></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div><div className="typeTabs">{(['expense','income','transfer'] as TransactionType[]).map(v=><button className={type===v?'selected':''} onClick={()=>setType(v)} key={v}>{v}</button>)}</div>{type==='expense'&&!editing&&<ReceiptScanner onResult={handleReceipt}/>}<label>Description<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={type==='income'?'Salary, refund...':type==='transfer'?'Move money...':'Groceries, dinner...'}/></label><label>Amount<input value={amount} onChange={e=>setAmount(e.target.value)} type="number" inputMode="decimal" placeholder="0.00"/></label><div className="formGrid"><label>From wallet<select value={walletId} onChange={e=>setWalletId(e.target.value)}>{data.wallets.length?<>{data.wallets.map(w=><option value={w.id} key={w.id}>{w.name} ({w.currency})</option>)}</>:<option value="">No wallets yet</option>}</select></label>{type==='transfer'?<label>To wallet<select value={toWalletId} onChange={e=>setToWalletId(e.target.value)}>{data.wallets.filter(w=>w.id!==walletId).map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select></label>:<label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{data.categories.map(c=><option key={c}>{c}</option>)}</select></label>}</div><div className="formGrid"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional"/></label></div><button className="primary" onClick={submit}>{editing?'Save changes':`Save ${type}`}</button></div></div>}
  {walletForm&&<div className="overlay" onClick={()=>setWalletForm(null)}><div className="sheet walletSheet" onClick={e=>e.stopPropagation()}><div className="sheetTop"><div><span className="eyebrow">{walletForm.id?'EDIT':'NEW'} WALLET</span><h2>{walletForm.id?'Edit wallet':'Add wallet'}</h2></div><button className="close" onClick={()=>setWalletForm(null)}><X/></button></div><label>Wallet name<input value={walletForm.name} onChange={e=>setWalletForm({...walletForm,name:e.target.value})} placeholder="e.g. Main account" autoFocus/></label><div className="formGrid"><label>Currency<select value={walletForm.currency} disabled={!!walletForm.id&&walletUsed(walletForm.id)} onChange={e=>setWalletForm({...walletForm,currency:e.target.value as 'USD'|'LBP'})}><option value="USD">USD — US Dollar</option><option value="LBP">LBP — Lebanese Pound</option></select>{walletForm.id&&walletUsed(walletForm.id)&&<small className="fieldHint">Currency is locked because this wallet has transaction history.</small>}</label><label>Opening balance<input type="number" inputMode="decimal" value={walletForm.openingBalance} onChange={e=>setWalletForm({...walletForm,openingBalance:e.target.value})}/></label></div><button className="primary" onClick={saveWallet}>{walletForm.id?'Save wallet':'Create wallet'}</button></div></div>}
  {dialog&&<div className="dialogOverlay" onClick={()=>setDialog(null)}><div className="dialogCard" onClick={e=>e.stopPropagation()}><div className={`dialogIcon ${dialog.kind==='danger'?'dangerIcon':'infoIcon'}`}>{dialog.kind==='danger'?<AlertTriangle/>:<Check/>}</div><h2>{dialog.title}</h2><p>{dialog.message}</p><div className="dialogActions"><button className="dialogCancel" onClick={()=>setDialog(null)}>{dialog.onConfirm?'Cancel':'Got it'}</button>{dialog.onConfirm&&<button className="dialogConfirm" onClick={confirmDialog}>{dialog.confirmLabel||'Confirm'}</button>}</div></div></div>}
 </main></div>
}
