import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowDownLeft, ArrowLeftRight, ArrowUpRight, BarChart3, Check, CreditCard, Home, Pencil, Plus, Settings, Trash2, WalletCards, X } from 'lucide-react'
import ReceiptScanner from './components/ReceiptScanner'
import NotePhotoPicker from './components/NotePhotoPicker'
import { Currency, defaultData, loadData, saveData, SpenzaData, Transaction, TransactionType, uid, Wallet } from './lib/db'

const money=(n:number,c:Currency|'USD'='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:c==='LBP'?0:2}).format(n)
const today=()=>new Date().toISOString().slice(0,10)
type Dialog={title:string;message:string;kind?:'danger'|'info';confirmLabel?:string;onConfirm?:()=>void}
type WalletForm={id?:string;name:string;currency:Currency;openingBalance:string}
type ReceiptSource={amount:number;currency?:Currency}
type InsightPeriod='daily'|'monthly'|'yearly'

export default function App(){
 const [data,setData]=useState<SpenzaData>(defaultData)
 const [ready,setReady]=useState(false)
 const [tab,setTab]=useState('Home')
 const [activityWalletId,setActivityWalletId]=useState<string|null>(null)
 const [insightWalletId,setInsightWalletId]=useState('')
 const [insightCategory,setInsightCategory]=useState('all')
 const [insightPeriod,setInsightPeriod]=useState<InsightPeriod>('monthly')
 const [insightDate,setInsightDate]=useState(today())
 const [open,setOpen]=useState(false)
 const [editing,setEditing]=useState<string|null>(null)
 const [dialog,setDialog]=useState<Dialog|null>(null)
 const [walletForm,setWalletForm]=useState<WalletForm|null>(null)
 const [receiptSource,setReceiptSource]=useState<ReceiptSource|null>(null)
 const [type,setType]=useState<TransactionType>('expense')
 const [title,setTitle]=useState('')
 const [amount,setAmount]=useState('')
 const [category,setCategory]=useState('Food')
 const [walletId,setWalletId]=useState('')
 const [toWalletId,setToWalletId]=useState('')
 const [date,setDate]=useState(today())
 const [note,setNote]=useState('')
 const [noteImages,setNoteImages]=useState<string[]>([])
 useEffect(()=>{loadData().then(d=>{setData(d);setReady(true)}).catch(()=>setReady(true))},[])
 useEffect(()=>{if(ready)saveData(data)},[data,ready])
 useEffect(()=>{if(!insightWalletId&&data.wallets[0])setInsightWalletId(data.wallets[0].id);if(insightWalletId&&!data.wallets.some(w=>w.id===insightWalletId))setInsightWalletId(data.wallets[0]?.id||'')},[data.wallets,insightWalletId])
 const rate=data.usdToLbpRate||89500
 const convert=(value:number,from:Currency,to:Currency)=>from===to?value:from==='USD'?value*rate:value/rate
 const walletBalance=(id:string)=>{const w=data.wallets.find(x=>x.id===id);if(!w)return 0;return data.transactions.reduce((b,t)=>{if(t.type==='income'&&t.walletId===id)return b+t.amount;if(t.type==='expense'&&t.walletId===id)return b-t.amount;if(t.type==='transfer'){if(t.walletId===id)return b-t.amount;if(t.toWalletId===id)return b+(t.exchangeRate?t.amount*t.exchangeRate:t.amount)}return b},w.openingBalance)}
 const walletUsed=(id:string)=>data.transactions.some(t=>t.walletId===id||t.toWalletId===id)
 const spent=useMemo(()=>data.transactions.filter(t=>t.type==='expense').reduce((a,t)=>{const w=data.wallets.find(w=>w.id===t.walletId);return a+(w?convert(t.amount,w.currency,'USD'):0)},0),[data])
 const income=useMemo(()=>data.transactions.filter(t=>t.type==='income').reduce((a,t)=>{const w=data.wallets.find(w=>w.id===t.walletId);return a+(w?convert(t.amount,w.currency,'USD'):0)},0),[data])
 const resetForm=()=>{setEditing(null);setType('expense');setTitle('');setAmount('');setCategory(data.categories[0]||'Other');setWalletId(data.wallets[0]?.id||'');setToWalletId(data.wallets[1]?.id||data.wallets[0]?.id||'');setDate(today());setNote('');setNoteImages([]);setReceiptSource(null)}
 const showAdd=()=>{resetForm();setOpen(true)}
 const edit=(t:Transaction)=>{setEditing(t.id);setType(t.type);setTitle(t.title);setAmount(String(t.amount));setCategory(t.category);setWalletId(t.walletId);setToWalletId(t.toWalletId||'');setDate(t.date);setNote(t.note||'');setNoteImages(t.noteImages||[]);setReceiptSource(null);setOpen(true)}
 const applyReceiptAmount=(source:ReceiptSource,targetWalletId:string)=>{const wallet=data.wallets.find(w=>w.id===targetWalletId);if(!wallet||!source.currency){setAmount(String(source.amount));return}const converted=convert(source.amount,source.currency,wallet.currency);setAmount(wallet.currency==='LBP'?String(Math.round(converted)):converted.toFixed(2))}
 useEffect(()=>{if(receiptSource)applyReceiptAmount(receiptSource,walletId)},[walletId,data.usdToLbpRate])
 const handleReceipt=(result:{amount:number;currency?:Currency;merchant?:string;rawText:string})=>{setType('expense');const source={amount:result.amount,currency:result.currency};setReceiptSource(source);applyReceiptAmount(source,walletId);setTitle('');setNote(result.currency?`Receipt scanned in ${result.currency}`:'Added from scanned receipt')}
 const transferRate=()=>{const from=data.wallets.find(w=>w.id===walletId);const to=data.wallets.find(w=>w.id===toWalletId);if(!from||!to||from.currency===to.currency)return 1;return from.currency==='USD'?rate:1/rate}
 const addCategory=()=>{const raw=window.prompt('New category name');const name=raw?.trim();if(!name)return;const existing=data.categories.find(c=>c.toLowerCase()===name.toLowerCase());if(existing){setCategory(existing);return}setData(d=>({...d,categories:[...d.categories,name]}));setCategory(name)}
 const submit=()=>{const n=Number(amount);if(!n||n<=0)return;if(type!=='expense'&&!title.trim())return;if(!walletId){setDialog({title:'Create a wallet first',message:'Add at least one wallet before saving a transaction.',kind:'info'});return}if(type==='transfer'&&!toWalletId){setDialog({title:'Choose a destination wallet',message:'Transfers need both a source wallet and a destination wallet.',kind:'info'});return}const now=new Date().toISOString();const old=data.transactions.find(t=>t.id===editing);const displayTitle=title.trim()||(type==='expense'?category:'Transaction');const tx:Transaction={id:editing||uid(),type,title:displayTitle,category:type==='transfer'?'Transfer':category,amount:n,walletId,toWalletId:type==='transfer'?toWalletId:undefined,exchangeRate:type==='transfer'?transferRate():undefined,date,note:note.trim()||undefined,noteImages:noteImages.length?noteImages:undefined,createdAt:old?.createdAt||now,updatedAt:now};setData(d=>({...d,transactions:editing?d.transactions.map(x=>x.id===editing?tx:x):[tx,...d.transactions]}));setOpen(false);resetForm()}
 const remove=(id:string)=>{const tx=data.transactions.find(t=>t.id===id);setDialog({title:'Delete transaction?',message:`${tx?.title||'This transaction'} will be permanently removed from your activity and balances.`,kind:'danger',confirmLabel:'Delete',onConfirm:()=>setData(d=>({...d,transactions:d.transactions.filter(t=>t.id!==id)}))})}
 const addWallet=()=>setWalletForm({name:'',currency:'USD',openingBalance:'0'})
 const editWallet=(w:Wallet)=>setWalletForm({id:w.id,name:w.name,currency:w.currency,openingBalance:String(w.openingBalance)})
 const saveWallet=()=>{if(!walletForm)return;const name=walletForm.name.trim();const opening=Number(walletForm.openingBalance);if(!name||Number.isNaN(opening))return;if(walletForm.id){const existing=data.wallets.find(w=>w.id===walletForm.id);if(!existing)return;const currency=walletUsed(existing.id)?existing.currency:walletForm.currency;setData(d=>({...d,wallets:d.wallets.map(w=>w.id===existing.id?{...w,name,currency,openingBalance:opening}:w)}))}else{const id=uid();setData(d=>({...d,wallets:[...d.wallets,{id,name,currency:walletForm.currency,openingBalance:opening}]}));if(!walletId)setWalletId(id)}setWalletForm(null)}
 const deleteWallet=(id:string)=>{const wallet=data.wallets.find(w=>w.id===id);if(!wallet)return;if(walletUsed(id)){setDialog({title:'Wallet is in use',message:'This wallet has transaction history. Reassign or delete those transactions before removing the wallet.',kind:'info'});return}setDialog({title:`Delete ${wallet.name}?`,message:'This wallet will be permanently removed from Spenza.',kind:'danger',confirmLabel:'Delete wallet',onConfirm:()=>setData(d=>({...d,wallets:d.wallets.filter(w=>w.id!==id)}))})}
 const resetAll=()=>setDialog({title:'Reset Spenza?',message:'All local wallets and transactions will be permanently cleared. This cannot be undone.',kind:'danger',confirmLabel:'Reset data',onConfirm:()=>setData(defaultData)})
 const confirmDialog=()=>{dialog?.onConfirm?.();setDialog(null)}
 const changeRate=(value:string)=>{const n=Number(value);if(n>0)setData(d=>({...d,usdToLbpRate:n}))}
 const openWalletActivity=(id:string)=>{setActivityWalletId(id);setTab('Activity')}
 const openAllActivity=()=>{setActivityWalletId(null);setTab('Activity')}
 const inInsightPeriod=(txDate:string)=>{if(insightPeriod==='daily')return txDate===insightDate;if(insightPeriod==='monthly')return txDate.slice(0,7)===insightDate.slice(0,7);return txDate.slice(0,4)===insightDate.slice(0,4)}
 const TxRow=({t}:{t:Transaction})=>{const w=data.wallets.find(x=>x.id===t.walletId);const sign=t.type==='income'?'+':t.type==='expense'?'-':'→';const photos=t.noteImages?.length||0;return <div className="tx"><div className={`txIcon ${t.type}`}>{t.type==='income'?<ArrowDownLeft/>:t.type==='transfer'?<ArrowLeftRight/>:<ArrowUpRight/>}</div><div className="txMain"><b>{t.title}</b><span>{t.category} · {w?.name||'No wallet'} · {t.date}{photos?` · 📷 ${photos}`:''}</span></div><strong className={t.type==='income'?'positive':''}>{sign}{money(t.amount,w?.currency||'USD')}</strong><div className="txActions"><button onClick={()=>edit(t)}><Pencil/></button><button onClick={()=>remove(t.id)}><Trash2/></button></div></div>}
 const selectedWallet=data.wallets.find(w=>w.id===walletId)
 const activityWallet=activityWalletId?data.wallets.find(w=>w.id===activityWalletId):undefined
 const activityTransactions=activityWalletId?data.transactions.filter(t=>t.walletId===activityWalletId||t.toWalletId===activityWalletId):data.transactions
 const insightWallet=data.wallets.find(w=>w.id===insightWalletId)
 const insightTransactions=data.transactions.filter(t=>t.walletId===insightWalletId&&inInsightPeriod(t.date)&&(insightCategory==='all'||t.category===insightCategory))
 const insightExpenses=insightTransactions.filter(t=>t.type==='expense').reduce((sum,t)=>sum+t.amount,0)
 const insightIncome=insightTransactions.filter(t=>t.type==='income').reduce((sum,t)=>sum+t.amount,0)
 const insightTransfers=insightTransactions.filter(t=>t.type==='transfer').reduce((sum,t)=>sum+t.amount,0)
 const insightPeriodLabel=insightPeriod==='daily'?insightDate:insightPeriod==='monthly'?new Date(`${insightDate.slice(0,7)}-01T00:00:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'}):insightDate.slice(0,4)
 const conversionLabel=receiptSource?.currency&&selectedWallet&&receiptSource.currency!==selectedWallet.currency?`${money(receiptSource.amount,receiptSource.currency)} → ${money(Number(amount)||0,selectedWallet.currency)} at 1 USD = ${rate.toLocaleString()} LBP`:null
 return <div className="shell"><main className="phone">
  {tab==='Home'&&<><header><div><span className="eyebrow">SPENZA · LOCAL MODE</span><h1>My finances</h1></div><button className="round" onClick={()=>setTab('Wallets')}><WalletCards size={19}/></button></header><section className="hero"><div className="heroTop"><span>Wallet balances</span><span className="pill">● Offline ready</span></div>{data.wallets.length?<div style={{display:'grid',gap:12,marginTop:16}}>{data.wallets.map(w=><button key={w.id} onClick={()=>openWalletActivity(w.id)} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,width:'100%',padding:'12px 0',border:0,borderBottom:'1px solid rgba(255,255,255,.12)',background:'transparent',color:'inherit',textAlign:'left'}}><span style={{display:'flex',flexDirection:'column',gap:3}}><b style={{fontSize:14}}>{w.name}</b><small style={{color:'#aab5b0'}}>{w.currency}</small></span><strong style={{fontFamily:'Playfair Display',fontSize:22}}>{money(walletBalance(w.id),w.currency)}</strong></button>)}</div>:<div style={{padding:'22px 0 6px',color:'#c7cfcb'}}>No wallets yet.</div>}</section><section className="quick"><button onClick={showAdd}><i><Plus/></i><span>Add</span></button><button onClick={()=>setTab('Wallets')}><i><WalletCards/></i><span>Wallets</span></button><button onClick={openAllActivity}><i><CreditCard/></i><span>Activity</span></button><button onClick={()=>setTab('Insights')}><i><BarChart3/></i><span>Insights</span></button></section>{data.wallets.length?<section className="walletStrip">{data.wallets.slice(0,2).map(w=><div key={w.id} role="button" tabIndex={0} onClick={()=>openWalletActivity(w.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')openWalletActivity(w.id)}} style={{cursor:'pointer'}}><span>{w.name}</span><b>{money(walletBalance(w.id),w.currency)}</b></div>)}</section>:<button className="emptyWalletCta" onClick={addWallet}><WalletCards/><span><b>Create your first wallet</b><small>Add cash, bank, or card balances before recording expenses.</small></span></button>}<section className="activity"><div className="sectionHead"><h2>Recent activity</h2><button onClick={openAllActivity}>All</button></div>{data.transactions.length?data.transactions.slice(0,5).map(t=><TxRow t={t} key={t.id}/>):<div className="empty compact">No transactions yet.</div>}</section></>}
  {tab==='Activity'&&<section className="page"><div className="pageHead"><div><span className="eyebrow">{activityWallet?'ACCOUNT ACTIVITY':'TRANSACTIONS'}</span><h1>{activityWallet?.name||'Activity'}</h1></div><button className="primarySmall" onClick={showAdd}><Plus/> Add</button></div>{activityWallet&&<div className="manage"><div><h2>{money(walletBalance(activityWallet.id),activityWallet.currency)}</h2><p>{activityWallet.currency} balance · showing transactions related to this account, including incoming and outgoing transfers.</p></div></div>}<div className="filters"><button className={!activityWalletId?'selected':''} onClick={()=>setActivityWalletId(null)}>All accounts</button><button onClick={()=>{resetForm();setType('expense');setOpen(true)}}>Expense</button><button onClick={()=>{resetForm();setType('income');setOpen(true)}}>Income</button><button onClick={()=>{resetForm();setType('transfer');setOpen(true)}}>Transfer</button></div>{activityTransactions.length?activityTransactions.map(t=><TxRow t={t} key={t.id}/>):<div className="empty">No transactions for this account yet.</div>}</section>}
  {tab==='Wallets'&&<section className="page"><div className="pageHead"><div><span className="eyebrow">YOUR MONEY</span><h1>Wallets</h1></div><button className="primarySmall" onClick={addWallet}><Plus/> Wallet</button></div>{data.wallets.length?<div className="walletGrid">{data.wallets.map(w=><article key={w.id}><div className="walletCardTop"><span>{w.currency}</span><div className="walletActions"><button className="walletEdit" onClick={()=>editWallet(w)}><Pencil/></button><button className="walletDelete" onClick={()=>deleteWallet(w.id)}><Trash2/></button></div></div><h2 onClick={()=>openWalletActivity(w.id)} style={{cursor:'pointer'}}>{w.name}</h2><strong onClick={()=>openWalletActivity(w.id)} style={{cursor:'pointer'}}>{money(walletBalance(w.id),w.currency)}</strong><small>Opening {money(w.openingBalance,w.currency)}</small></article>)}</div>:<div className="empty">No wallets yet.</div>}</section>}
  {tab==='Insights'&&<section className="page"><span className="eyebrow">FILTERED ANALYTICS</span><h1>Insights</h1>{data.wallets.length?<><div className="manage" style={{marginTop:20}}><div className="formGrid"><label>Account<select value={insightWalletId} onChange={e=>setInsightWalletId(e.target.value)}>{data.wallets.map(w=><option key={w.id} value={w.id}>{w.name} ({w.currency})</option>)}</select></label><label>Category<select value={insightCategory} onChange={e=>setInsightCategory(e.target.value)}><option value="all">All categories</option>{data.categories.map(c=><option key={c} value={c}>{c}</option>)}</select></label></div><div className="typeTabs" style={{marginTop:10,marginBottom:10}}>{(['daily','monthly','yearly'] as InsightPeriod[]).map(p=><button key={p} className={insightPeriod===p?'selected':''} onClick={()=>setInsightPeriod(p)}>{p}</button>)}</div><label style={{display:'block',fontSize:11,fontWeight:600}}>Reference date<input type="date" value={insightDate} onChange={e=>setInsightDate(e.target.value)} style={{display:'block',width:'100%',marginTop:7,padding:13,border:'1px solid #dfddd6',borderRadius:13,background:'#fff'}}/></label></div>{insightWallet&&<><div className="manage"><span className="eyebrow">{insightPeriodLabel.toUpperCase()} · {insightCategory==='all'?'ALL CATEGORIES':insightCategory.toUpperCase()}</span><h2 style={{marginTop:6}}>{insightWallet.name}</h2><p>{insightWallet.currency} account · current balance {money(walletBalance(insightWallet.id),insightWallet.currency)}</p></div><div className="insightGrid"><article><span>Expenses</span><strong>{money(insightExpenses,insightWallet.currency)}</strong></article><article><span>Income</span><strong>{money(insightIncome,insightWallet.currency)}</strong></article><article><span>Transactions</span><strong>{insightTransactions.length}</strong></article><article><span>Transfers out</span><strong>{money(insightTransfers,insightWallet.currency)}</strong></article></div><h2 className="subTitle">Spending by category</h2>{data.categories.map(c=>{const value=data.transactions.filter(t=>t.type==='expense'&&t.walletId===insightWallet.id&&inInsightPeriod(t.date)&&t.category===c&&(insightCategory==='all'||c===insightCategory)).reduce((sum,t)=>sum+t.amount,0);if(!value)return null;const pct=insightExpenses?Math.min(100,(value/insightExpenses)*100):0;return <div className="categoryRow" key={`${insightWallet.id}-${c}`}><span>{c}</span><div><i style={{width:`${pct}%`}}/></div><b>{money(value,insightWallet.currency)}</b></div>})}{!insightExpenses&&<div className="empty compact">No expenses for this account, category, and period.</div>}</>}</>:<div className="empty">Create a wallet to see insights.</div>}</section>}
  {tab==='Settings'&&<section className="page"><span className="eyebrow">SPENZA</span><h1>Settings</h1><div className="manage"><div><h2>Exchange rate</h2><p>Used for USD/LBP receipt conversion, wallet totals, analytics, and transfers.</p><label className="settingsField">1 USD = <input type="number" inputMode="decimal" value={rate} onChange={e=>changeRate(e.target.value)}/> LBP</label></div></div><div className="manage"><div><h2>Data storage</h2><p>Your transactions and attached note photos are saved locally in this browser using IndexedDB. Supabase cloud sync comes next.</p></div></div><button className="danger" onClick={resetAll}>Reset local data</button></section>}
  <nav>{[['Home',Home],['Activity',CreditCard],['Add',Plus],['Insights',BarChart3],['Settings',Settings]].map(([label,Icon]:any)=><button key={label} className={tab===label?'active':label==='Add'?'addNav':''} onClick={()=>{if(label==='Add')showAdd();else{if(label==='Activity')setActivityWalletId(null);setTab(label)}}}><Icon size={20}/><span>{label}</span></button>)}</nav>
  {open&&<div className="overlay" onClick={()=>setOpen(false)}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheetTop"><div><span className="eyebrow">{editing?'EDIT':'NEW'} TRANSACTION</span><h2>{editing?'Edit transaction':'Add transaction'}</h2></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div><div className="typeTabs">{(['expense','income','transfer'] as TransactionType[]).map(v=><button className={type===v?'selected':''} onClick={()=>{setType(v);if(v!=='expense')setReceiptSource(null)}} key={v}>{v}</button>)}</div>{type==='expense'&&<ReceiptScanner onResult={handleReceipt}/>}<label>Description {type==='expense'&&<small className="fieldHint">Optional</small>}<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={type==='income'?'Salary, refund...':type==='transfer'?'Move money...':'Optional description'}/></label><label>Amount{selectedWallet&&<small className="fieldHint">Saved in {selectedWallet.currency}</small>}<input value={amount} onChange={e=>setAmount(e.target.value)} type="number" inputMode="decimal" placeholder="0.00"/></label>{conversionLabel&&<div className="conversionNotice"><b>Converted receipt total</b><span>{conversionLabel}</span></div>}<div className="formGrid"><label>From wallet<select value={walletId} onChange={e=>setWalletId(e.target.value)}><option value="">Choose wallet</option>{data.wallets.map(w=><option value={w.id} key={w.id}>{w.name} ({w.currency})</option>)}</select></label>{type==='transfer'?<label>To wallet<select value={toWalletId} onChange={e=>setToWalletId(e.target.value)}><option value="">Choose wallet</option>{data.wallets.filter(w=>w.id!==walletId).map(w=><option value={w.id} key={w.id}>{w.name} ({w.currency})</option>)}</select></label>:<label>Category<div style={{display:'flex',gap:8,alignItems:'stretch'}}><select value={category} onChange={e=>setCategory(e.target.value)} style={{flex:1}}>{data.categories.map(c=><option key={c}>{c}</option>)}</select><button type="button" className="primarySmall" onClick={addCategory} style={{marginTop:7,whiteSpace:'nowrap'}}><Plus size={14}/> New</button></div></label>}</div><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional note"/></label><div className="noteAttachmentLabel">Photos</div><NotePhotoPicker images={noteImages} onChange={setNoteImages}/><button className="primary" onClick={submit}>{editing?'Save changes':`Save ${type}`}</button></div></div>}
  {walletForm&&<div className="overlay" onClick={()=>setWalletForm(null)}><div className="sheet walletSheet" onClick={e=>e.stopPropagation()}><div className="sheetTop"><div><span className="eyebrow">{walletForm.id?'EDIT':'NEW'} WALLET</span><h2>{walletForm.id?'Edit wallet':'Add wallet'}</h2></div><button className="close" onClick={()=>setWalletForm(null)}><X/></button></div><label>Wallet name<input value={walletForm.name} onChange={e=>setWalletForm({...walletForm,name:e.target.value})} placeholder="e.g. Main account" autoFocus/></label><div className="formGrid"><label>Currency<select value={walletForm.currency} disabled={!!walletForm.id&&walletUsed(walletForm.id)} onChange={e=>setWalletForm({...walletForm,currency:e.target.value as Currency})}><option value="USD">USD — US Dollar</option><option value="LBP">LBP — Lebanese Pound</option></select></label><label>Opening balance<input type="number" inputMode="decimal" value={walletForm.openingBalance} onChange={e=>setWalletForm({...walletForm,openingBalance:e.target.value})}/></label></div><button className="primary" onClick={saveWallet}>{walletForm.id?'Save wallet':'Create wallet'}</button></div></div>}
  {dialog&&<div className="dialogOverlay" onClick={()=>setDialog(null)}><div className="dialogCard" onClick={e=>e.stopPropagation()}><div className={`dialogIcon ${dialog.kind==='danger'?'dangerIcon':'infoIcon'}`}>{dialog.kind==='danger'?<AlertTriangle/>:<Check/>}</div><h2>{dialog.title}</h2><p>{dialog.message}</p><div className="dialogActions"><button className="dialogCancel" onClick={()=>setDialog(null)}>{dialog.onConfirm?'Cancel':'Got it'}</button>{dialog.onConfirm&&<button className="dialogConfirm" onClick={confirmDialog}>{dialog.confirmLabel||'Confirm'}</button>}</div></div></div>}
 </main></div>
}